import assert from 'node:assert/strict';
import {checkQuestions,validateAnswers,assess,parseWritingReview,adaptiveAdvice,nextCheckBlock} from '../lib/assessment.ts';
const all=Object.fromEntries(checkQuestions.map(q=>[q.id,q.answer]));
const sample='Ik hou van koken en ik maak graag soep voor mijn vrienden. Gisteren heb ik groenten gekocht op de markt. Daarna ging ik naar huis. Volgende week ga ik een ander recept proberen, omdat ik graag nieuwe smaken ontdek.';
const input={answers:all,writing:sample,assisted:false,review:null};
assert.equal(validateAnswers({'b2-1':1},true),null,'cannot skip foundations');
assert.equal(validateAnswers({'a1-1':0},true),null,'incomplete check cannot assign a level');
assert.equal(validateAnswers({...all,unknown:0}),null,'unknown question rejected');
assert.equal(validateAnswers({...all,'a1-1':99}),null,'out of range rejected');
assert.deepEqual(validateAnswers(all,true),all);
assert.equal(nextCheckBlock({}),'A1');
assert.equal(nextCheckBlock(all),null);
const failed=Object.fromEntries(checkQuestions.filter(q=>q.level==='A1').map(q=>[q.id,-1]));
assert.deepEqual(validateAnswers(failed,true),failed);
assert.equal(nextCheckBlock(failed),null);
assert.equal(assess({...input,answers:failed}).level,null);
assert.equal(validateAnswers({...all,'a1-1':-1,'a1-2':-1},true),null,'higher blocks after failed block rejected');
assert.equal(assess(input).level,'B2');
assert.equal(assess({...input,assisted:true}).level,null,'help is not independent evidence');
assert.equal(parseWritingReview({level:'C2',quote:sample.slice(0,40),focus:'samenhang'},sample),null);
assert.equal(parseWritingReview({level:'B2',quote:'invented evidence not in text',focus:'samenhang'},sample),null);
assert.equal(parseWritingReview('broken JSON',sample),null);
const valid=parseWritingReview({level:'B2',quote:sample.slice(0,40),focus:'samenhang'},sample);
assert.equal(valid.level,'A2','short writing caps the provisional writing level');
assert.equal(assess({...input,review:valid}).level,'A2','conservative combination');
const a={id:'test',createdAt:'2026-10-01T00:00:00Z',input,result:assess({...input,review:valid})};
const ev=(id,level='B1',score=4,assisted=false)=>({exerciseId:id,level,score,total:4,skill:'Lezen',assisted,date:'2026-10-02T00:00:00Z'});
assert.equal(adaptiveAdvice(a,[ev('a')]).level,'A2');
assert.equal(adaptiveAdvice(a,[ev('a'),ev('a')]).level,'A2','same exercise cannot count twice');
assert.equal(adaptiveAdvice(a,[ev('a'),ev('b')]).level,'B1');
assert.equal(adaptiveAdvice(a,[ev('a'),ev('b','B1',4,true)]).level,'A2');
assert.equal(adaptiveAdvice(a,[ev('a','A2',1),ev('b','A2',1)]).level,'A1');
assert.equal(adaptiveAdvice(a,[{...ev('a'),date:'2026-09-30'},ev('b')]).level,'A2');
assert.equal(adaptiveAdvice(null,[ev('a'),ev('b')]).level,null);
console.log('24 assessment and adaptation assertions passed');
