'use client';
import {createContext,useContext,useEffect,useState,type ReactNode} from 'react';
import {Palette,Sun,Moon,Monitor,RotateCcw,Check} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {B} from './translation';
const palettes=[
 {id:'autumn',name:'Warme herfst',description:'Crème & zachte aardetinten',swatch:'#e8dcc2',accent:'terracotta',light:['#f8f6f1','#fffefa','#eeefe6','#eeebe2','#34382f','#64685d','#deded3'],dark:['#20251f','#292f27','#272e24','#353d31','#eeeade','#b5bbab','#515948']},
 {id:'ocean',name:'Aan zee',description:'Helder & fris blauw',swatch:'#cbe4ec',accent:'ocean',light:['#f1f7fb','#ffffff','#e4eff5','#e4edf3','#203746','#526b7c','#cedce4'],dark:['#142530','#1c303d','#192c38','#2a404e','#e5f1f9','#aac2d2','#425b6b']},
 {id:'lavender',name:'Lavendel',description:'Lila & zachte paarstinten',swatch:'#e3d8ee',accent:'purple',light:['#f7f4fb','#fffefe','#eee7f5','#eee8f5','#3d3049','#70607c','#ddd2e5'],dark:['#251e30','#30273d','#2b2336','#3e324b','#f2eafb','#c4b3d4','#5e4b71']},
 {id:'forest',name:'In het groen',description:'Rustige salie & bosgroen',swatch:'#d2e2d0',accent:'forest',light:['#f3f7f1','#fdfffc','#e5eee0','#e5ecdf','#293e2c','#576b55','#cfddc9'],dark:['#19281d','#233529','#203024','#304736','#e5f3e3','#abc5ad','#48624e']},
 {id:'rose',name:'Zachte roos',description:'Lichtroze & warm bordeaux',swatch:'#efdae0',accent:'rose',light:['#fcf4f6','#fffdfd','#f5e6eb','#f1e6eb','#4b303b','#7c5e6b','#e4cfd7'],dark:['#2e1d26','#3a2631','#33232c','#4b3240','#fae8ef','#d0b1bf','#6c4b5c']},
 {id:'minimal',name:'Helder papier',description:'Rustig & zonder kleurtint',swatch:'#e4e6e9',accent:'slate',light:['#f6f7f9','#ffffff','#eceef1','#e9ecf0','#232a34','#586270','#cdd3dc'],dark:['#1b1e24','#252a32','#22262e','#343b47','#edf1f8','#b8c1cf','#525e70']}
];
const accents=[{id:'terracotta',name:'Terracotta',light:'#98492f',dark:'#edaa87'},{id:'forest',name:'Bosgroen',light:'#356340',dark:'#a3d5a8'},{id:'ocean',name:'Oceaan',light:'#216383',dark:'#91cdea'},{id:'purple',name:'Paars',light:'#74479d',dark:'#cfb1f3'},{id:'rose',name:'Framboos',light:'#a13b62',dark:'#efa7c2'},{id:'teal',name:'Petrol',light:'#176864',dark:'#89d4ca'},{id:'gold',name:'Oker',light:'#825b16',dark:'#e9c779'},{id:'slate',name:'Grafiet',light:'#495567',dark:'#c0cede'}];
const fonts=[{id:'friendly',name:'Vertrouwd',detail:'Trebuchet & Georgia',body:"'Trebuchet MS',Arial,sans-serif",heading:"Georgia,'Times New Roman',serif"},{id:'modern',name:'Modern',detail:'Systeemlettertype',body:'system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif',heading:'system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif'},{id:'classic',name:'Klassiek',detail:'Georgia',body:"Georgia,'Times New Roman',serif",heading:"Georgia,'Times New Roman',serif"},{id:'clear',name:'Extra helder',detail:'Verdana',body:'Verdana,Geneva,sans-serif',heading:'Verdana,Geneva,sans-serif'}];
type Preferences={palette:string;accent:string;font:string;mode:'light'|'dark'|'system';size:'normal'|'large'|'larger';motion:boolean};
const defaults:Preferences={palette:'autumn',accent:'terracotta',font:'friendly',mode:'light',size:'normal',motion:true};
const AppearanceContext=createContext<{preferences:Preferences;change:(p:Partial<Preferences>)=>void;reset:()=>void}>({preferences:defaults,change:()=>{},reset:()=>{}});
export function AppearanceProvider({children}:{children:ReactNode}){
 const [preferences,setPreferences]=useState(defaults),[loaded,setLoaded]=useState(false),[systemDark,setSystemDark]=useState(false);
 useEffect(()=>{try{const raw=JSON.parse(localStorage.getItem('taalcoach-appearance')||'null');if(raw){setPreferences({palette:palettes.some(p=>p.id===raw.palette)?raw.palette:defaults.palette,accent:accents.some(a=>a.id===raw.accent)?raw.accent:defaults.accent,font:fonts.some(f=>f.id===raw.font)?raw.font:defaults.font,mode:['light','dark','system'].includes(raw.mode)?raw.mode:defaults.mode,size:['normal','large','larger'].includes(raw.size)?raw.size:defaults.size,motion:raw.motion!==false})}else if(localStorage.getItem('taalcoach-theme')==='dark')setPreferences({...defaults,mode:'dark'})}catch{}setLoaded(true);const media=matchMedia('(prefers-color-scheme: dark)');setSystemDark(media.matches);const update=()=>setSystemDark(media.matches);media.addEventListener('change',update);return()=>media.removeEventListener('change',update)},[]);
 useEffect(()=>{if(!loaded)return;const dark=preferences.mode==='dark'||preferences.mode==='system'&&systemDark,palette=palettes.find(p=>p.id===preferences.palette)!,accent=accents.find(a=>a.id===preferences.accent)!,font=fonts.find(f=>f.id===preferences.font)!,colors=dark?palette.dark:palette.light,root=document.documentElement;const [background,card,sidebar,secondary,foreground,muted,border]=colors,primary=dark?accent.dark:accent.light;
 const vars:Record<string,string>={background,card,sidebar,secondary,foreground,'card-foreground':foreground,popover:card,'popover-foreground':foreground,'secondary-foreground':foreground,'muted-foreground':muted,muted:secondary,border,input:border,primary,'primary-foreground':dark?'#182129':'#ffffff',accent:secondary,'accent-foreground':foreground,ring:primary,'sidebar-foreground':foreground,'sidebar-border':border,'sidebar-accent':secondary,'sidebar-accent-foreground':foreground,'sidebar-primary':primary,'sidebar-primary-foreground':dark?'#182129':'#ffffff','sidebar-ring':primary,green:primary,'green-soft':secondary,'orange-soft':secondary,'purple-soft':secondary,'font-body':font.body,'font-heading':font.heading,'text-scale':preferences.size==='large'?'1.125':preferences.size==='larger'?'1.25':'1'};
 Object.entries(vars).forEach(([key,value])=>root.style.setProperty('--'+key,value));root.dataset.theme=dark?'dark':'light';root.dataset.palette=preferences.palette;root.dataset.font=preferences.font;root.dataset.motion=preferences.motion?'on':'off';root.style.colorScheme=dark?'dark':'light';try{localStorage.setItem('taalcoach-appearance',JSON.stringify(preferences))}catch{}
 },[preferences,loaded,systemDark]);
 return <AppearanceContext.Provider value={{preferences,change:p=>setPreferences(v=>({...v,...p})),reset:()=>setPreferences(defaults)}}>{children}</AppearanceContext.Provider>
}
export function AppearanceDialog({open,onOpenChange}:{open:boolean;onOpenChange:(open:boolean)=>void}){const {preferences:p,change,reset}=useContext(AppearanceContext);return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="appearance-dialog"><DialogHeader><DialogTitle><Palette size={25}/> Jouw vormgeving</DialogTitle><DialogDescription><B>Maak je leerplek prettig om naar te kijken. Je keuzes worden automatisch op dit apparaat bewaard.</B></DialogDescription></DialogHeader>
 <section><h3><B>Licht & donker</B></h3><div className="appearance-modes">{[{id:'light',name:'Licht',icon:Sun},{id:'dark',name:'Donker',icon:Moon},{id:'system',name:'Automatisch',icon:Monitor}].map(m=><button key={m.id} aria-pressed={p.mode===m.id} onClick={()=>change({mode:m.id as Preferences['mode']})}><m.icon size={19}/><B>{m.name}</B></button>)}</div></section>
 <section><h3><B>Kies een sfeer</B></h3><div className="palette-grid">{palettes.map(t=><button key={t.id} aria-pressed={p.palette===t.id} onClick={()=>change({palette:t.id,accent:t.accent})}><span className="palette-preview" style={{background:t.light[0]}}><i style={{background:t.swatch}}/><i style={{background:accents.find(a=>a.id===t.accent)!.light}}/>{p.palette===t.id&&<Check size={18}/>}</span><b><B>{t.name}</B></b><small><B>{t.description}</B></small></button>)}</div></section>
 <section><h3><B>Accentkleur</B></h3><p><B>Voor knoppen, links en actieve onderdelen.</B></p><div className="accent-options">{accents.map(a=><button key={a.id} aria-pressed={p.accent===a.id} aria-label={a.name} title={a.name} onClick={()=>change({accent:a.id})}><span style={{background:a.light}}>{p.accent===a.id&&<Check size={18} color="white"/>}</span><small><B>{a.name}</B></small></button>)}</div></section>
 <section><h3><B>Lettertype</B></h3><div className="font-options">{fonts.map(f=><button key={f.id} aria-pressed={p.font===f.id} onClick={()=>change({font:f.id})}><span style={{fontFamily:f.body}}>Aa</span><b><B>{f.name}</B></b><small>{f.detail}</small></button>)}</div></section>
 <section><h3><B>Tekstgrootte</B></h3><div className="appearance-modes">{[{id:'normal',name:'Standaard'},{id:'large',name:'Groot'},{id:'larger',name:'Extra groot'}].map(s=><button key={s.id} aria-pressed={p.size===s.id} onClick={()=>change({size:s.id as Preferences['size']})}><B>{s.name}</B></button>)}</div></section>
 <label className="motion-setting"><input type="checkbox" checked={!p.motion} onChange={e=>change({motion:!e.target.checked})}/><span><b><B>Minder beweging</B></b><small><B>Schakel animaties en overgangen uit.</B></small></span></label>
 <div className="appearance-sample"><span className="eyebrow"><B>ZO ZIET HET ERUIT</B></span><h2><B>Kleine stappen, nieuwe woorden.</B></h2><p><B>Een fijne leerplek helpt je om met aandacht te oefenen.</B></p><span className="sample-button"><B>Jouw accentkleur</B></span></div>
 <div className="appearance-actions"><button className="text-button" onClick={reset}><RotateCcw size={16}/><B>Herstel standaard</B></button><button className="primary-button" onClick={()=>onOpenChange(false)}><B>Klaar</B></button></div>
 </DialogContent></Dialog>}
