'use client';
import {useCoach} from '@/components/learning/coach-preferences';
import {useState,useRef,useEffect,useCallback} from 'react';
import {Gamepad2,Layers,KeyRound,Play,Pause,RotateCcw,Trophy,Heart,Volume2,VolumeX} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {PipMascot} from './pip-mascot';
import {nounSets,memorySets,spellingSets,shuffled,initialCatch,advanceCatch,revealedWord,type ArcadeLevel,type CatchState} from '@/lib/arcade';
type Mode='catcher'|'memory'|'spelling';
type Result={score:number;summary:string;success:boolean};
const modes=[{id:'catcher' as const,title:'Woordenvanger',label:'BEWEEG & VANG',description:'Beweeg je coach en vang alleen woorden met het juiste lidwoord.',icon:Gamepad2,skill:'Lidwoorden',time:'1 minuut'},{id:'memory' as const,title:'Woordenmemory',label:'DRAAI & ONTDEK',description:'Zoek de woorden die bij elkaar horen. Hoeveel paren onthoud jij?',icon:Layers,skill:'Woordenschat',time:'6 paren'},{id:'spelling' as const,title:'Letterkluis',label:'RAAD & ONTGRENDEL',description:'Kraak vijf woorden met een aanwijzing en je eigen letterkeuzes.',icon:KeyRound,skill:'Spelling',time:'5 woorden'}];
function useAutoPause(setPaused:(value:boolean)=>void){useEffect(()=>{const pause=()=>setPaused(true),hidden=()=>{if(document.hidden)pause()};window.addEventListener('blur',pause);document.addEventListener('visibilitychange',hidden);return()=>{window.removeEventListener('blur',pause);document.removeEventListener('visibilitychange',hidden)}},[setPaused])}
export function ArcadeGames({onComplete}:{onComplete:()=>void}){const {text:coachText,coach}=useCoach();
 const [mode,setMode]=useState<Mode|null>(null),[level,setLevel]=useState<ArcadeLevel>('A2'),[started,setStarted]=useState(false),[result,setResult]=useState<Result|null>(null),[run,setRun]=useState(''),[saved,setSaved]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[sound,setSound]=useState(false);
 const soundContext=useRef<AudioContext|null>(null),meta=modes.find(m=>m.id===mode),lock=useRef(false),activeRun=useRef('');activeRun.current=run;
 function newRun(){const id=crypto.randomUUID();setRun(id);setStarted(true);setResult(null);setSaved(false);setSaving(false);setError('');lock.current=false}
 function open(next:Mode){setMode(next);setRun('');setStarted(false);setResult(null);setSaved(false);setError('')}
 const finish=useCallback((r:Result)=>{setResult(r)},[]);
 function tone(good:boolean){if(!sound)return;try{const context=soundContext.current||new AudioContext();soundContext.current=context;void context.resume();const oscillator=context.createOscillator(),gain=context.createGain();oscillator.type='sine';oscillator.frequency.value=good?660:220;gain.gain.setValueAtTime(.045,context.currentTime);gain.gain.exponentialRampToValueAtTime(.001,context.currentTime+.12);oscillator.connect(gain);gain.connect(context.destination);oscillator.start();oscillator.stop(context.currentTime+.13)}catch{}}
 useEffect(()=>()=>{void soundContext.current?.close()},[]);
 async function save(){if(!result||!meta||lock.current||saved)return;lock.current=true;setSaving(true);setError('');const id=run;try{const r=await fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'activity',kind:'arcade-'+meta.id,skill:meta.skill,id,detail:JSON.stringify({title:meta.title,level,score:result.score,summary:result.summary,success:result.success})})});const j=await r.json() as {error?:string};if(!r.ok)throw Error(j.error||'Opslaan is niet gelukt.');if(id===activeRun.current){setSaved(true);onComplete()}}catch(e){if(id===activeRun.current)setError((e as Error).message)}finally{if(id===activeRun.current){setSaving(false);lock.current=false}}}
 return <><div className="arcade-grid">{modes.map((m,i)=><button key={m.id} className={`arcade-card arcade-card-${m.id}`} onClick={()=>open(m.id)}><span className="arcade-card-top"><m.icon size={26}/><span>0{i+1}</span></span><span className="arcade-kicker">{m.label}</span><h2>{m.title}</h2><p>{m.description}</p><span className="arcade-card-bottom"><span>{m.time} · A2–B2</span><b>Spelen <Play size={15}/></b></span></button>)}</div>
 <Dialog open={!!mode} onOpenChange={o=>{if(!o){setMode(null);setRun('');setStarted(false);activeRun.current=''}}}><DialogContent className="arcade-dialog"><DialogHeader><DialogTitle>{meta?.title}</DialogTitle><DialogDescription>{meta?.description}</DialogDescription></DialogHeader><div className="arcade-toolbar"><span className="arcade-kicker">SPEELHAL</span><button onClick={()=>setSound(v=>!v)} aria-pressed={sound} aria-label={sound?'Spelgeluid uitzetten':'Spelgeluid aanzetten'}>{sound?<Volume2 size={19}/>:<VolumeX size={19}/>}</button></div>
 {!started?<div className="arcade-start"><PipMascot size="large"/><h3>{mode==='catcher'?'Klaar om woorden te vangen?':mode==='memory'?'Een goed geheugen begint met kijken.':'Welke woorden zitten in de kluis?'}</h3><p>{mode==='catcher'?coachText('Vang 10 juiste woorden in 60 seconden. Beweeg met ← →, de knoppen of sleep Pip. Verkeerd gevangen of gemist? Dan verlies je een hartje.'):mode==='memory'?'Draai twee kaarten om. Vind zes paren van woorden met een verwante betekenis. Je mag rustig nadenken.':'Raad het woord bij de aanwijzing. Klik op letters of gebruik je toetsenbord. Je hebt zes verkeerde pogingen per woord.'}</p><label>Niveau<select value={level} onChange={e=>setLevel(e.target.value as ArcadeLevel)}><option>A2</option><option>B1</option><option>B2</option></select></label><button className="primary-button" onClick={newRun}><Play size={18}/>Start spel</button><small>Geen AI nodig · resultaat bewaren levert 20 XP op</small></div>:result?<div className="arcade-result" role="status"><PipMascot size="large" mood="celebrating"/><span className="arcade-kicker">RONDE AFGEROND</span><h3>{result.success?'Mooi gespeeld!':'Je hebt weer iets geoefend.'}</h3><strong className="arcade-score">{result.score}<small>punten</small></strong><p>{result.summary}</p><div className="arcade-result-actions"><button className="primary-button" disabled={saved||saving} onClick={()=>void save()}><Trophy size={18}/>{saved?'Bewaard · +20 XP':saving?'Bewaren…':'Bewaar resultaat · 20 XP'}</button><button className="outline-button" disabled={saving} onClick={newRun}><RotateCcw size={16}/>Nog een keer</button></div>{error&&<p role="alert">{error}</p>}</div>:mode==='catcher'?<Catcher key={run} level={level} onEnd={finish} tone={tone}/>:mode==='memory'?<Memory key={run} level={level} onEnd={finish} tone={tone}/>:<LetterVault key={run} level={level} onEnd={finish} tone={tone}/>}
 </DialogContent></Dialog></>;
}
type GameProps={level:ArcadeLevel;onEnd:(r:Result)=>void;tone:(good:boolean)=>void};
function PauseButton({paused,setPaused}:{paused:boolean;setPaused:(p:boolean)=>void}){return <button onClick={()=>setPaused(!paused)} aria-label={paused?'Spel hervatten':'Spel pauzeren'}>{paused?<Play size={18}/>:<Pause size={18}/>}</button>}
function Catcher({level,onEnd,tone}:GameProps){const {text:coachText,coach}=useCoach();
 const [game,setGame]=useState<CatchState>(initialCatch),[paused,setPaused]=useState(false),[slow,setSlow]=useState(false),[target]=useState<'de'|'het'>(()=>Math.random()<.5?'de':'het'),[player,setPlayer]=useState(50);
 const deck=useRef(shuffled(nounSets[level])),state=useRef(game),x=useRef(player),field=useRef<HTMLDivElement|null>(null),callbacks=useRef({onEnd,tone});callbacks.current={onEnd,tone};
 useAutoPause(setPaused);useEffect(()=>{field.current?.focus()},[]);
 useEffect(()=>{if(paused)return;let frame=0,last=performance.now();const tick=(now:number)=>{const before=state.current,next=advanceCatch(before,(now-last)/1000,x.current,target,deck.current,slow);last=now;state.current=next;setGame(next);if(before.score!==next.score||before.lives!==next.lives)callbacks.current.tone(next.score>before.score);if(next.ended){callbacks.current.onEnd({score:next.score,summary:`${next.caught} juiste woorden gevangen · ${Math.ceil(next.elapsed)} seconden gespeeld.`,success:next.caught>=10});return}frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[paused,slow,target]);
 function move(value:number){const next=Math.max(10,Math.min(90,value));x.current=next;setPlayer(next)}
 return <><div className="arcade-hud"><b>Vang: <em>{target}</em></b><span>{game.caught}/10</span><span>{Math.max(0,60-Math.floor(game.elapsed))}s</span><span aria-label={`${game.lives} levens`}>{Array.from({length:game.lives},(_,i)=><Heart size={16} fill="currentColor" key={i}/>)}</span><PauseButton paused={paused} setPaused={setPaused}/></div><div ref={field} tabIndex={0} className="catch-field" role="application" aria-label={`Woordenvanger. Vang ${target}-woorden. Beweeg met de pijltjestoetsen. Spatie pauzeert.`} onKeyDown={e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();if(!paused)move(x.current+(e.key==='ArrowLeft'?-15:15))}if(e.key===' '){e.preventDefault();setPaused(p=>!p)}}} onPointerDown={e=>{if(paused)return;e.currentTarget.setPointerCapture(e.pointerId);const r=e.currentTarget.getBoundingClientRect();move((e.clientX-r.left)/r.width*100)}} onPointerMove={e=>{if(!paused&&e.currentTarget.hasPointerCapture(e.pointerId)){const r=e.currentTarget.getBoundingClientRect();move((e.clientX-r.left)/r.width*100)}}}>
 <span className="catch-score" aria-hidden="true">{game.score.toString().padStart(3,'0')}<small>{game.combo>1?`${game.combo} OP RIJ`:'PUNTEN'}</small></span><span className="catch-lane"/>
 {game.items.map(w=><span className="falling-word" key={w.id} style={{left:`${w.x}%`,top:`${w.y}%`}}>{w.word}</span>)}<span className="catch-fox" style={{left:`${player}%`}}><PipMascot size="small" decorative/><b>{target}</b></span>{paused&&<div className="arcade-paused"><b>Even pauze</b><button className="primary-button" onClick={e=>{e.stopPropagation();setPaused(false);field.current?.focus()}}>Verder spelen</button></div>}</div><div className="catch-controls"><button aria-label={coachText("Pip naar links")} disabled={paused} onClick={()=>move(x.current-15)}>←</button><label><input type="checkbox" checked={slow} onChange={e=>setSlow(e.target.checked)}/>Rustiger tempo</label><button aria-label={coachText("Pip naar rechts")} disabled={paused} onClick={()=>move(x.current+15)}>→</button></div><p className="arcade-feedback" role="status">{game.feedback||`Laat woorden met ${target==='de'?'het':'de'} voorbijvallen.`}</p></>;
}
function Memory({level,onEnd,tone}:GameProps){
 const [cards]=useState(()=>shuffled(memorySets[level].flatMap(([a,b],pair)=>[{text:a,pair},{text:b,pair}]))),[flipped,setFlipped]=useState<number[]>([]),[matched,setMatched]=useState<number[]>([]),[moves,setMoves]=useState(0),[seconds,setSeconds]=useState(0),[paused,setPaused]=useState(false),[feedback,setFeedback]=useState('Draai twee kaarten om.');
 const callbacks=useRef({onEnd,tone});callbacks.current={onEnd,tone};useAutoPause(setPaused);
 useEffect(()=>{if(paused)return;const t=setInterval(()=>setSeconds(s=>s+1),1000);return()=>clearInterval(t)},[paused]);
 useEffect(()=>{if(flipped.length!==2||paused)return;const [a,b]=flipped,correct=cards[a].pair===cards[b].pair;const t=setTimeout(()=>{callbacks.current.tone(correct);if(correct){const next=[...matched,cards[a].pair];setMatched(next);setFeedback(`${cards[a].text} en ${cards[b].text} horen bij elkaar.`);if(next.length===6)callbacks.current.onEnd({score:Math.max(20,120-(moves-6)*5),summary:`6 paren gevonden in ${moves} beurten en ${seconds} seconden.`,success:true})}else setFeedback('Nog geen paar. Onthoud de plekken en probeer opnieuw.');setFlipped([])},correct?550:1100);return()=>clearTimeout(t)},[flipped,paused]);
 function flip(index:number){if(paused||flipped.length===2||flipped.includes(index)||matched.includes(cards[index].pair))return;setFlipped([...flipped,index]);if(flipped.length===1)setMoves(m=>m+1)}
 return <><div className="arcade-hud"><b>{matched.length}/6 paren</b><span>{moves} beurten</span><span>{seconds}s</span><PauseButton paused={paused} setPaused={setPaused}/></div><div className="memory-board">{cards.map((card,i)=>{const open=flipped.includes(i)||matched.includes(card.pair);return <button key={i} onClick={()=>flip(i)} disabled={paused||matched.includes(card.pair)||flipped.length===2} className={`memory-tile ${open?'flipped':''} ${matched.includes(card.pair)?'matched':''}`} aria-label={open?card.text:`Kaart ${i+1}, omdraaien`} aria-pressed={open}><span>{open?card.text:<><span aria-hidden="true">✦</span><small>{i+1}</small></>}</span></button>})}{paused&&<div className="arcade-paused"><b>Even pauze</b><button className="primary-button" onClick={()=>setPaused(false)}>Verder spelen</button></div>}</div><p className="arcade-feedback" role="status">{feedback}</p></>;
}
function LetterVault({level,onEnd,tone}:GameProps){
 const [words]=useState(()=>shuffled(spellingSets[level])),[round,setRound]=useState(0),[guessed,setGuessed]=useState<string[]>([]),[score,setScore]=useState(0),[solved,setSolved]=useState(0),[paused,setPaused]=useState(false);
 const field=useRef<HTMLDivElement|null>(null),current=words[round],wrong=guessed.filter(c=>!current.word.includes(c)).length,won=revealedWord(current.word,guessed),done=won||wrong>=6;
 useAutoPause(setPaused);useEffect(()=>{field.current?.focus()},[round]);
 function guess(c:string){if(paused||done||guessed.includes(c))return;setGuessed(g=>[...g,c]);tone(current.word.includes(c))}
 function next(){const points=won?Math.max(10,40-wrong*5):0,newScore=score+points,newSolved=solved+(won?1:0);if(round===4){onEnd({score:newScore,summary:`${newSolved} van de 5 woorden ontgrendeld.`,success:newSolved>=3});return}setScore(newScore);setSolved(newSolved);setRound(r=>r+1);setGuessed([])}
 return <div ref={field} tabIndex={0} className="letter-vault" role="application" aria-label="Letterkluis. Typ een letter of kies een letterknop." onKeyDown={e=>{if(!e.ctrlKey&&!e.metaKey&&!e.altKey&&/^[a-z]$/i.test(e.key)){e.preventDefault();guess(e.key.toLowerCase())}}}><div className="arcade-hud"><b>Kluis {round+1}/5</b><span>{score} punten</span><span>{Math.max(0,6-wrong)} pogingen</span><PauseButton paused={paused} setPaused={setPaused}/></div><div className="vault-clue"><KeyRound size={28}/><p>{current.clue}</p></div><div className="vault-word" aria-label={done?current.word:'Het woord: '+[...current.word].map(c=>guessed.includes(c)?c:'leeg').join(', ')}>{[...current.word].map((c,i)=><span key={i} className={done&&!guessed.includes(c)?'revealed':''}>{done||guessed.includes(c)?c:'·'}</span>)}</div>{done?<div className="vault-explanation" role="status"><h3>{won?'Kluis geopend!':'Dit was het woord.'}</h3><p>{current.tip}</p><button className="primary-button" onClick={next}>{round===4?'Bekijk resultaat':'Volgende kluis'}</button></div>:<div className="letter-keyboard" aria-label="Kies een letter">{'abcdefghijklmnopqrstuvwxyz'.split('').map(c=><button key={c} onClick={()=>guess(c)} disabled={paused||guessed.includes(c)} className={guessed.includes(c)?current.word.includes(c)?'hit':'miss':''} aria-label={`Letter ${c}`}>{c}</button>)}</div>}{paused&&<div className="arcade-paused"><b>Even pauze</b><button className="primary-button" onClick={()=>setPaused(false)}>Verder spelen</button></div>}</div>;
}
