'use client';
import {useCoach} from '@/components/learning/coach-preferences';
import {useState,useEffect,useCallback,useRef} from 'react';
import {BookOpen,Headphones,NotebookPen,SpellCheck,MessagesSquare,ArrowUpRight,CheckCircle2,Save,RotateCcw} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {B} from './translation';
import {PipAssistant} from './pip-assistant';
import {exerciseHelpContext} from '@/lib/pip-help';
import {categories,exercises,canComplete,wordCount,type Category,type Exercise,type ExerciseData} from '@/lib/exercises';
export const exerciseIcons={grammatica:BookOpen,spelling:SpellCheck,lezen:BookOpen,luisteren:Headphones,schrijven:NotebookPen,formuleren:MessagesSquare};
type SavedWork={exercise_id:string;data:ExerciseData;completed:number;updated_at:string};
type Result={correct:boolean[];score:number;total:number;xp:number};
async function api(body?:unknown){const r=await fetch('/api/exercises',body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined);const j=await r.json() as any;if(!r.ok)throw Error(j.error||'Opslaan lukt nu niet. Probeer opnieuw.');return j;}
export function ExerciseRoutes({onChoose}:{onChoose:(category:Category)=>void}){return <div className="exercise-routes">{categories.map(c=>{const Icon=exerciseIcons[c.id];return <button key={c.id} className={`exercise-route route-${c.id}`} onClick={()=>onChoose(c.id)}><Icon size={26}/><h3><B>{c.name}</B></h3><p><B>{c.description}</B></p><span><B>{exercises.filter(e=>e.category===c.id).length} oefeningen · {c.id==='grammatica'?'A1–B1':'A2–B2'}</B><ArrowUpRight size={18}/></span></button>})}</div>}
export function ExerciseLibrary({initialCategory='all',initialFocus,recommendedLevel,onComplete}:{initialCategory?:Category|'all';initialFocus?:string;recommendedLevel?:string;onComplete:()=>void}){
 const [category,setCategory]=useState<string>(initialCategory),[focus,setFocus]=useState(initialFocus||'all'),[level,setLevel]=useState('all'),[work,setWork]=useState<SavedWork[]>([]),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState<Exercise|null>(null);
 const load=useCallback(async()=>{try{const j=await api();setWork(j.work);setLoaded(true);setError('')}catch(e){setError((e as Error).message)}},[]);
 useEffect(()=>{load()},[load]);
 const filtered=exercises.filter(e=>(category==='all'||e.category===category)&&(level==='all'||e.level===level)&&(focus==='all'||e.focus===focus));
 return <><div className="page-heading"><div><div className="season-label"><NotebookPen size={16}/> ELKE VAARDIGHEID TELT</div><h1><B>Jouw oefenbibliotheek.</B></h1><p><B>Kies een vaardigheid en werk op je eigen tempo. Met uitleg, voorbeelden en opgeslagen voortgang.</B></p></div></div>
 <div className="exercise-toolbar"><div className="exercise-filters" aria-label="Vaardigheid">{[{id:'all',name:'Alles'},...categories].map(c=><button key={c.id} aria-pressed={category===c.id} onClick={()=>{setCategory(c.id);setFocus('all')}}><B>{c.name}</B></button>)}</div><label className="exercise-level"><B>Niveau</B><select value={level} onChange={e=>setLevel(e.target.value)}><option value="all">Alle niveaus</option>{['A1','A2','B1','B2'].map(l=><option key={l}>{l}</option>)}</select></label></div>
 {focus!=='all'&&<div className="adaptation-note"><b>Jouw focus: {focus}</b><button className="text-button" onClick={()=>setFocus('all')}>Toon alle grammatica</button></div>}<p className="library-meta"><B>{filtered.length} oefeningen · {work.filter(w=>w.completed).length} van {exercises.length} afgerond</B></p>
 {error&&<div className="error-banner" role="alert">{error}<button onClick={load}>Opnieuw proberen</button></div>}
 <div className="exercise-grid">{filtered.map(ex=>{const Icon=exerciseIcons[ex.category],saved=work.find(w=>w.exercise_id===ex.id);return <article key={ex.id} className="exercise-card"><div className="exercise-card-top"><span className={`exercise-icon route-${ex.category}`}><Icon size={24}/></span><span className="tag">{ex.level} · {ex.minutes} min{ex.level===recommendedLevel?' · jouw oefenniveau':''}</span></div><span className="eyebrow"><B>{categories.find(c=>c.id===ex.category)?.name}</B></span><h2>{ex.title}</h2><p><B>{ex.description}</B></p><div className="exercise-card-meta"><span><B>{ex.writing?'Schrijfopdracht + zelfcontrole':`${ex.questions.length} vragen + uitleg`}</B></span>{saved?.completed?<span className="completed-label"><CheckCircle2 size={15}/><B>Afgerond</B></span>:<span>20 XP</span>}</div><button className="outline-button" disabled={!loaded} onClick={()=>setSelected(ex)}><B>{!loaded?'Voortgang laden…':saved?.completed?'Bekijk of herhaal':saved?'Verder oefenen':'Start oefening'}</B><ArrowUpRight size={17}/></button></article>})}</div>
 {selected&&<ExerciseDialog key={selected.id} ex={selected} initial={work.find(w=>w.exercise_id===selected.id)} onClose={()=>{setSelected(null);load()}} onSaved={()=>{load();onComplete()}}/>}</>;
}
function ExerciseDialog({ex,initial,onClose,onSaved}:{ex:Exercise;initial?:SavedWork;onClose:()=>void;onSaved:()=>void}){const {text:coachText,coach}=useCoach();
 const [data,setData]=useState<ExerciseData>(initial?.data||{answers:ex.questions.map(()=>''),text:'',checks:(ex.writing?.checklist||[]).map(()=>false)}),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState(''),[result,setResult]=useState<Result|null>(null),[speed,setSpeed]=useState(1),[helpQuestion,setHelpQuestion]=useState(0);
 const audio=useRef<HTMLAudioElement|null>(null),resultEl=useRef<HTMLDivElement|null>(null),lock=useRef(false);
 const words=wordCount(data.text),valid=canComplete(ex,data);
 useEffect(()=>{if(!dirty)return;const handler=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler)},[dirty]);
 useEffect(()=>{if(result)resultEl.current?.scrollIntoView({behavior:'smooth',block:'center'})},[result]);
 function update(next:ExerciseData){setData(next);setDirty(true);setStatus('');setResult(null)}
 async function save(complete:boolean){if(lock.current)return false;lock.current=true;setBusy(true);setError('');try{const j=await api({exerciseId:ex.id,data,complete});setDirty(false);setStatus(complete?'Resultaat opgeslagen.':'Concept opgeslagen. Je kunt later verder.');if(complete)setResult(j);onSaved();return true}catch(e){setError((e as Error).message);return false}finally{lock.current=false;setBusy(false)}}
 async function close(){if(busy)return;if(dirty&&!await save(false))return;onClose()}
 return <Dialog open onOpenChange={open=>{if(!open)close()}}><DialogContent className="exercise-dialog exercise-with-pip" onEscapeKeyDown={e=>{if(document.querySelector('.pip-embedded .pip-help-panel'))e.preventDefault()}}><div className="exercise-scroll"><DialogHeader><span className="eyebrow">{ex.level} · {ex.minutes} MIN · {categories.find(c=>c.id===ex.category)?.name}</span><DialogTitle>{ex.title}</DialogTitle><DialogDescription><B>{ex.description}</B></DialogDescription></DialogHeader>
 {ex.audio&&<section className="listening-player"><h3><Headphones size={20}/>Luister naar het fragment</h3><p>Een natuurlijk ingesproken fragment met een AI-stem. Luister zo vaak als je wilt en beantwoord daarna de vragen.</p><audio ref={audio} controls preload="metadata" src={ex.audio} onError={()=>setError('Het audiofragment kan niet worden geladen. Herlaad de pagina of gebruik de uitgeschreven tekst hieronder.')} aria-label={`Luisterfragment: ${ex.title}`}/><div className="playback-speeds"><span>Snelheid</span>{[.8,1,1.2].map(s=><button key={s} aria-pressed={s===speed} onClick={()=>{setSpeed(s);if(audio.current)audio.current.playbackRate=s}}>{s===1?'Normaal':s===.8?'Rustiger':'Sneller'}</button>)}</div><details><summary onClick={()=>{if(!data.assisted)update({...data,assisted:true})}}>Toon uitgeschreven tekst</summary><p className="exercise-passage">{ex.passage}</p></details></section>}
 {ex.passage&&!ex.audio&&<section className="exercise-reading"><h3>{ex.category==='grammatica'?'De uitleg':'Lees de tekst'}</h3><p className="exercise-passage">{ex.passage}</p></section>}
 {ex.writing?<><section className="writing-prompt"><h3>De opdracht</h3><p>{ex.writing.prompt}</p></section><label className="writing-field">Jouw tekst<textarea value={data.text} rows={10} maxLength={10000} disabled={busy} onChange={e=>update({...data,text:e.target.value,checks:data.checks.map(()=>false)})} placeholder="Begin hier met schrijven…"/></label><div className="word-count"><span>{words} woorden</span><span>{ex.writing.minWords}–{ex.writing.maxWords} woorden gevraagd</span></div><fieldset className="writing-checklist"><legend>Lees je tekst na</legend><p>Vink aan wat je hebt gecontroleerd. Bij een wijziging aan je tekst loop je de lijst opnieuw na.</p>{ex.writing.checklist.map((item,i)=><label key={item}><input type="checkbox" disabled={busy||!!result} checked={data.checks[i]||false} onChange={e=>update({...data,checks:data.checks.map((c,n)=>n===i?e.target.checked:c)})}/><span>{item}</span></label>)}</fieldset><details className="model-answer"><summary>Bekijk een voorbeeldtekst</summary><p>Dit is één mogelijke uitwerking. Jouw eigen formulering mag anders zijn.</p><p className="exercise-passage">{ex.writing.example}</p></details><p className="muted writing-note">Je beoordeelt deze tekst zelf met de checklist en het voorbeeld. Je krijgt hier geen automatische taalbeoordeling.</p></>:<div className="exercise-questions">{ex.questions.map((q,i)=><fieldset key={i} onFocus={()=>setHelpQuestion(i)} onPointerDown={()=>setHelpQuestion(i)} className={'exercise-question '+(result?(result.correct[i]?'is-correct':'needs-practice'):'')}><legend>{i+1}. {q.prompt}</legend><button className="question-help-select" type="button" aria-pressed={helpQuestion===i} onClick={()=>setHelpQuestion(i)}>{helpQuestion===i?coachText('Pip kijkt mee met deze vraag'):coachText('Laat Pip met deze vraag meekijken')}</button>{q.options?<div className="exercise-options">{q.options.map((option,n)=><label key={n} className={data.answers[i]===String(n)?'selected':''}><input type="radio" name={`question-${i}`} checked={data.answers[i]===String(n)} disabled={busy||!!result} onChange={()=>update({...data,answers:data.answers.map((a,index)=>index===i?String(n):a)})}/><span>{option}</span></label>)}</div>:<input className="spelling-answer" aria-label={`Antwoord op vraag ${i+1}`} value={data.answers[i]||''} autoComplete="off" spellCheck={false} disabled={busy||!!result} onChange={e=>update({...data,answers:data.answers.map((a,index)=>index===i?e.target.value:a)})}/>}{result&&<div className="question-feedback"><b>{result.correct[i]?'Goed gedaan.':'Nog even oefenen.'}</b>{!result.correct[i]&&<p>Het antwoord: <strong>{q.options?q.options[q.correct!]:q.accepted?.[0]}</strong></p>}<p>{q.explanation}</p></div>}</fieldset>)}</div>}
 <label className="learning-check"><input type="checkbox" checked={!!data.assisted} disabled={busy||!!result} onChange={e=>update({...data,assisted:e.target.checked})}/>Ik gebruikte hulp, vertaling of een voorbeeld. Dit resultaat telt als oefenervaring, niet als zelfstandig bewijs voor mijn niveau.</label>{result&&<div ref={resultEl} tabIndex={-1} className="exercise-result" role="status"><CheckCircle2 size={28}/><h3>{ex.writing?'Je tekst is bewaard en zelf nagekeken.':`${result.score} van de ${result.total} goed`}</h3><p>{result.xp?`Je hebt ${result.xp} XP verdiend.`:'Je voortgang is opgeslagen. Voor deze oefening ontving je eerder al XP.'}</p>{!ex.writing&&<p>Lees de uitleg bij elke vraag. Je kunt zo vaak herhalen als je wilt.</p>}</div>}
 {error&&<p className="error-banner" role="alert">{error}</p>}{status&&!result&&<p role="status" className="save-status">{status}</p>}
 <div className="exercise-actions">{result?<><button className="outline-button" onClick={()=>{setResult(null);setStatus('');if(!ex.writing){setData({...data,answers:ex.questions.map(()=> '')});setDirty(true)}}}><RotateCcw size={17}/>{ex.writing?'Tekst bewerken':'Opnieuw oefenen'}</button><button className="primary-button" onClick={close}>Terug naar oefeningen</button></>:<><button className="outline-button" disabled={busy||(!dirty&&!!initial)} onClick={()=>save(false)}><Save size={17}/>{busy?'Opslaan…':'Bewaar concept'}</button><button className="primary-button" disabled={busy||!valid} onClick={()=>save(true)}>{busy?'Opslaan…':ex.writing?'Afronden & bewaren':'Controleer antwoorden'}</button></>}</div>
 {!result&&<p className="exercise-save-hint">{dirty?'Je hebt wijzigingen. Bij sluiten bewaren we automatisch je concept.':'Je voortgang wordt gekoppeld aan je account.'}{!valid&&(ex.writing?' Rond je woordenaantal en de checklist af om de opdracht te voltooien.':' Vul alle antwoorden in om ze te controleren.')}</p>}
 </div><PipAssistant onHelpUsed={()=>{if(!data.assisted)update({...data,assisted:true})}} embedded context={exerciseHelpContext(ex,data,helpQuestion)} answers={ex.questions[helpQuestion]?.accepted||(ex.questions[helpQuestion]?.options?[ex.questions[helpQuestion].options![ex.questions[helpQuestion].correct!]]:[])}/></DialogContent></Dialog>;
}
