'use client';
import {useCoach,PersonalizeCoachButton} from '@/components/learning/coach-preferences';
import {B} from '@/components/learning/translation';
import {useState,useEffect,useRef,useCallback} from 'react';
import {Palette,Leaf,LayoutDashboard,Compass,BookOpen,ChartNoAxesCombined,GraduationCap,Flame,Sparkles,Sun,Moon,ChevronRight,Clock,Mic,MessageCircle,Headphones,Briefcase,School,Building2,Check,Plus,Send,Phone,PhoneOff,MicOff,Trophy,Target,Volume2,NotebookPen,Coffee,Search,Play,RotateCcw,X,CheckCircle2,LoaderCircle,Settings,BookMarked,Lightbulb,Users} from 'lucide-react';
import {Sidebar,SidebarProvider,SidebarContent,SidebarHeader,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Progress} from '@/components/ui/progress';
import {missions} from '@/lib/missions';

import {LanguageSwitcher,useLanguage,T} from '@/components/learning/translation';
import {Profile,defaultProfile} from '@/lib/profile';
import {useLearningState} from '@/components/learning/learning-state';
import {LearningJourney,JourneyHomeCard,type LearningDestination} from '@/components/learning/learning-journey';
import {LevelCheck,LevelSummary} from '@/components/learning/level-check';
import {LanguageAtelier,type ReadingSeed} from '@/components/learning/language-atelier';
import {exercises} from '@/lib/exercises';
import type {Focus} from '@/lib/learning';
import {ProfileForm} from '@/components/learning/profile-form';
import {NewsPanel} from '@/components/learning/news-panel';
import {usePipPage} from '@/components/learning/pip-assistant';
import {LocalAISetup,useLocalAI} from '@/components/learning/local-ai-setup';
import {localCompletion} from '@/lib/local-ai';
import {reflectionMessages,reviewedReflection} from '@/lib/coach-feedback';
import {coachCharacter} from '@/lib/coach-preferences';
import {localCoachPersonality} from '@/lib/coach-personality';

import {VoiceControls} from '@/components/learning/voice-controls';
import {ArcadeGames} from '@/components/learning/arcade-games';
import {PipMascot,type PipMood} from '@/components/learning/pip-mascot';
import {ExerciseLibrary,ExerciseRoutes} from '@/components/learning/exercise-library';
import {AppearanceDialog} from '@/components/learning/appearance';
import {type Category} from '@/lib/exercises';
import {ChallengeGames} from '@/components/learning/challenge-games';
import {TeacherDashboard} from '@/components/learning/teacher-dashboard';

type Mission=typeof missions[number];
type Message={role:'user'|'assistant';content:string};
type Activity={id:string;kind:string;skill:string;xp:number;date:string;detail:string};
type Lesson={id:string;title:string;module:string;body:string;status:string};
type UserRole='teacher_admin'|'student';
const nav=[{id:'home',label:'Mijn leerplek',icon:LayoutDashboard},{id:'journey',label:'Mijn leerroute',icon:Compass},{id:'atelier',label:'Taalatelier',icon:Palette},{id:'exercises',label:'Oefeningen',icon:NotebookPen},{id:'missions',label:'AI-coach',icon:MessageCircle},{id:'content',label:'Leeshoek & vaknieuws',icon:BookOpen},{id:'games',label:'Taalspellen',icon:Trophy},{id:'progress',label:'Mijn voortgang',icon:ChartNoAxesCombined}];
const skills=['Spelling','Lezen','Luisteren','Schrijven','Formuleren','Lidwoorden','Enkelvoud & meervoud','Zinsbouw','Schooltaal','Woordenschat'];
const articles=[{title:'Een goede start op je stage',field:'Werk & loopbaan',time:3,icon:Briefcase,text:'Op je eerste stagedag ontmoet je jouw begeleider. Samen bespreken jullie de werkzaamheden. Stel gerust een vraag als een instructie niet duidelijk is. Het is handig om belangrijke afspraken op te schrijven. Aan het einde van de dag kun je reflecteren: wat ging goed en wat wil je morgen oefenen?'},{title:'Samen werken aan een project',field:'School & studie',time:4,icon:School,text:'Tijdens een project werk je samen met andere studenten. Eerst verdelen jullie de taken. Daarna maken jullie een planning. Een duidelijke deadline helpt om het werk op tijd af te ronden. Geef elkaar feedback en luister naar andere ideeën. Zo draagt iedereen bij aan het resultaat.'},{title:'Aandacht voor de patiënt',field:'Zorg & welzijn',time:3,icon:Building2,text:'In de zorg is goed luisteren belangrijk. Een patiënt vertelt soms niet meteen wat er aan de hand is. Stel een open vraag en geef iemand de tijd om te antwoorden. Leg een handeling rustig uit. Controleer daarna of de uitleg duidelijk is. Een vriendelijk gesprek kan veel vertrouwen geven.'},{title:'Van idee naar een website',field:'ICT & techniek',time:4,icon:NotebookPen,text:'Een ontwikkelaar begint met een ontwerp. De gebruiker moet gemakkelijk kunnen vinden wat hij zoekt. Daarom test het team een prototype. Met de feedback wordt het ontwerp verbeterd. Daarna controleert de ontwikkelaar of elke functie werkt. Goed samenwerken is net zo belangrijk als programmeren.'}];
const dictionary:Record<string,{article:string;meaning:string;synonym:string;en:string}>={begeleider:{article:'de',meaning:'Iemand die je helpt en ondersteunt tijdens je stage of studie.',synonym:'coach',en:'supervisor'},werkzaamheden:{article:'de (meervoud)',meaning:'Het werk en de taken die je uitvoert.',synonym:'taken',en:'duties'},instructie:{article:'de',meaning:'Een uitleg over hoe je iets moet doen.',synonym:'aanwijzing',en:'instruction'},afspraken:{article:'de (meervoud)',meaning:'Dingen die je samen hebt besloten.',synonym:'overeenkomsten',en:'agreements'},reflecteren:{article:'werkwoord',meaning:'Terugkijken op wat je deed en wat je daarvan leert.',synonym:'nadenken over',en:'to reflect'},project:{article:'het',meaning:'Een opdracht waaraan je een bepaalde tijd werkt.',synonym:'opdracht',en:'project'},planning:{article:'de',meaning:'Een overzicht van wat je wanneer gaat doen.',synonym:'tijdschema',en:'schedule'},deadline:{article:'de',meaning:'Het laatste moment waarop iets klaar moet zijn.',synonym:'einddatum',en:'deadline'},feedback:{article:'de',meaning:'Een reactie die je helpt je werk te verbeteren.',synonym:'terugkoppeling',en:'feedback'},resultaat:{article:'het',meaning:'Wat je bereikt na je werk.',synonym:'uitkomst',en:'result'},patiënt:{article:'de',meaning:'Iemand die zorg of een behandeling krijgt.',synonym:'zorgontvanger',en:'patient'},handeling:{article:'de',meaning:'Iets wat je doet, bijvoorbeeld tijdens het verzorgen.',synonym:'actie',en:'action'},vertrouwen:{article:'het',meaning:'Het gevoel dat je op iemand kunt rekenen.',synonym:'zekerheid',en:'trust'},ontwikkelaar:{article:'de',meaning:'Iemand die bijvoorbeeld software of websites maakt.',synonym:'programmeur',en:'developer'},ontwerp:{article:'het',meaning:'Een plan dat laat zien hoe iets eruit gaat zien.',synonym:'vormgeving',en:'design'},gebruiker:{article:'de',meaning:'Iemand die een product of website gebruikt.',synonym:'gebruiker van een product',en:'user'},prototype:{article:'het',meaning:'Een eerste versie om een idee te testen.',synonym:'proefmodel',en:'prototype'},functie:{article:'de',meaning:'Wat een onderdeel kan doen.',synonym:'mogelijkheid',en:'function'}};
const questions=[{q:'Welk lidwoord hoort bij “gesprek”?',a:['De gesprek','Het gesprek','Een de gesprek','Gesprek het'],correct:1,why:'Gesprek is een het-woord: het gesprek. In het meervoud: de gesprekken.',skill:'Lidwoorden'},{q:'Wat is het meervoud van “afspraak”?',a:['Afspraaks','Afspraakken','Afspraken','Afspraaken'],correct:2,why:'Eén afspraak, twee afspraken. De lange a-klank blijft behouden.',skill:'Enkelvoud & meervoud'},{q:'Welke zin is correct?',a:['Morgen ik ga naar school.','Ik morgen naar school ga.','Naar school morgen ik ga.','Morgen ga ik naar school.'],correct:3,why:'Na “morgen” staat de persoonsvorm “ga”, daarna het onderwerp “ik”.',skill:'Zinsbouw'},{q:'Wat betekent “reflecteren”?',a:['Terugkijken en ervan leren','Zo snel mogelijk werken','Iets uit je hoofd leren','Een afspraak afzeggen'],correct:0,why:'Bij reflecteren denk je na over wat goed ging en wat je kunt verbeteren.',skill:'Schooltaal'},{q:'Hoe vraag je beleefd om hulp?',a:['Doe dit nu.','Je moet mij helpen.','Zou je dit nog eens kunnen uitleggen?','Dat begrijp jij niet.'],correct:2,why:'Met “zou je … kunnen” formuleer je een vriendelijk verzoek.',skill:'Schooltaal'}];
const grid=['SCHOOLAB','TKLMNOPQ','AWERKXYZ','GRCDEFGH','EIMNOPQR','BSUVWXYZ','LESABCDE','PLANNING'];
const locations:Record<string,number[]>={SCHOOL:[0,1,2,3,4,5],STAGE:[0,8,16,24,32],WERK:[17,18,19,20],LES:[48,49,50],PLANNING:[56,57,58,59,60,61,62,63]};
const iconFor=(m:Mission)=>m.icon==='school'?School:m.icon==='work'?Briefcase:Building2;
function Picker({value,onChange,items}:{value:string;onChange:(v:string)=>void;items:string[]}){return <Select value={value} onValueChange={onChange}><SelectTrigger className="picker"><SelectValue/></SelectTrigger><SelectContent>{items.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select>}
async function request(path:string,body?:unknown){const r=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined);const data=await r.json() as any;if(!r.ok)throw new Error(data.error||'Er ging iets mis. Probeer opnieuw.');return data;}

export default function Home(){const {text:coachText,coach}=useCoach();
 const {choose:chooseLanguage,language}=useLanguage();
 const localAI=useLocalAI();
 const learning=useLearningState();
 const [levelCheck,setLevelCheck]=useState(false),[readingSeed,setReadingSeed]=useState<ReadingSeed|null>(null),[exerciseFocus,setExerciseFocus]=useState<Focus|undefined>();
 const clearReadingSeed=useCallback(()=>setReadingSeed(null),[]);
 const [voiceMood,setVoiceMood]=useState<PipMood>('idle');
 const [profile,setProfile]=useState<Profile>(defaultProfile);
 useEffect(()=>{setLevel(profile.adaptive&&learning.data.advice.level?learning.data.advice.level:profile.level)},[profile.level,profile.adaptive,learning.data.advice.level]);
 const [appearance,setAppearance]=useState(false),[exerciseCategory,setExerciseCategory]=useState<Category|'all'>('all');
 const [view,setView]=useState('home'),[level,setLevel]=useState('B1'),[goal,setGoal]=useState('Mbo'),[category,setCategory]=useState('Alles'),[role,setRole]=useState<UserRole>('student');
 const [activities,setActivities]=useState<Activity[]>([]),[lessons,setLessons]=useState<Lesson[]>([]),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[ready,setReady]=useState(false);
 const [mission,setMission]=useState<Mission|null>(null),[messages,setMessages]=useState<Message[]>([]),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[feedback,setFeedback]=useState(''),[sessionId,setSessionId]=useState(''),[saved,setSaved]=useState(false);
 const [calling,setCalling]=useState(false),[connecting,setConnecting]=useState(false),[muted,setMuted]=useState(false),[callStatus,setCallStatus]=useState(''),[seconds,setSeconds]=useState(0);
 const callAttempt=useRef(0),coachAttempt=useRef(0),coachAbort=useRef<AbortController|null>(null);
 const pc=useRef<RTCPeerConnection|null>(null),stream=useRef<MediaStream|null>(null),audio=useRef<HTMLAudioElement|null>(null),chatEnd=useRef<HTMLDivElement|null>(null);
 const [article,setArticle]=useState<number|null>(null),[word,setWord]=useState(''),[field,setField]=useState('Alles'),[game,setGame]=useState<string|null>(null),[q,setQ]=useState(0),[answer,setAnswer]=useState<number|null>(null),[score,setScore]=useState(0),[quizDone,setQuizDone]=useState(false),[gameId,setGameId]=useState(''),[quizSkills,setQuizSkills]=useState<string[]>([]),[selected,setSelected]=useState<number[]>([]),[found,setFound]=useState<string[]>([]),[gameSaved,setGameSaved]=useState(false);
 usePipPage({id:view,title:nav.find(n=>n.id===view)?.label||'Lessenmaker',level,description:'De leerling bekijkt '+(nav.find(n=>n.id===view)?.label||'de lessenmaker')+'. Leg uit hoe je hier kunt oefenen; vraag welke stap lastig is.'});
 const [readLesson,setReadLesson]=useState<Lesson|null>(null);
 const [editor,setEditor]=useState<Lesson|null>(null),[generating,setGenerating]=useState(false),[settings,setSettings]=useState(false);
 const reload=useCallback(async()=>{try{const d=await request('/api/state');setActivities(d.activities);setLessons(d.lessons);setLoaded(true);setError('');}catch(e){setError((e as Error).message);}},[]);
 useEffect(()=>{reload();request('/api/profile').then(d=>{setProfile(d.profile);setGoal(d.profile.goal);chooseLanguage(localStorage.getItem('taalcoach-language')||d.profile.language)}).catch(e=>setError(e.message));request('/api/me').then(d=>setRole(d.user?.role||'student')).catch(()=>{});request('/api/coach').then(d=>setReady(d.ready)).catch(()=>{});},[reload,chooseLanguage]);
 useEffect(()=>{chatEnd.current?.scrollIntoView({behavior:'smooth'});},[messages,busy]);
 useEffect(()=>{if(!calling)return;const id=setInterval(()=>setSeconds(s=>s+1),1000);return()=>clearInterval(id)},[calling]);
 const endCall=useCallback(()=>{callAttempt.current++;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;pc.current?.close();pc.current=null;if(audio.current){audio.current.pause();audio.current.srcObject=null;}setCalling(false);setConnecting(false);setMuted(false);setCallStatus('');},[]);
 useEffect(()=>()=>{coachAttempt.current++;coachAbort.current?.abort();callAttempt.current++;stream.current?.getTracks().forEach(t=>t.stop());pc.current?.close();},[]);
 const startMission=useCallback((m:Mission)=>{coachAttempt.current++;coachAbort.current?.abort();setBusy(false);endCall();setMission(m);setMessages([{role:'assistant',content:coachText(m.opening)}]);setFeedback('');setInput('');setSaved(false);setSessionId(crypto.randomUUID());setNotice('');},[endCall,coachText]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const controller=new AbortController();Promise.resolve(context.registerTool({name:'start_language_mission',title:'Start een taalmissie',description:'Open een gekozen oefengesprek. Start geen microfoon en voltooit geen oefening.',inputSchema:{type:'object',properties:{missionId:{type:'string',enum:missions.map(m=>m.id)}},required:['missionId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(i:any)=>{const m=missions.find(m=>m.id===i.missionId);if(!m)throw new Error('Onbekende missie');startMission(m);return {missionId:m.id,status:'opened'};}},{signal:controller.signal})).catch(()=>{});return()=>controller.abort()},[startMission]);

 async function record(kind:string,skill:string,id:string,detail:string){await request('/api/state',{type:'activity',kind,skill,id,detail});await reload();}
 async function send(spoken?:string){
  const utterance=(spoken??input).trim();
  if(!utterance||busy||!mission||localAI.status!=='ready')return;
  const next:Message[]=[...messages,{role:'user',content:utterance.slice(0,2000)}],attempt=++coachAttempt.current,c=new AbortController();coachAbort.current=c;
  setMessages(next);setInput('');setBusy(true);setNotice('');
  try{const text=await localCompletion([{role:'system',content:localCoachPersonality(coach)+'\n'+JSON.stringify({role:mission.role,situation:mission.description,goals:mission.goals,level,goal,field:profile.field,interests:profile.interests})},...next.slice(-10)],{signal:c.signal});if(attempt===coachAttempt.current)setMessages([...next,{role:'assistant',content:text}]);}
  catch(e){if(attempt===coachAttempt.current){setMessages(messages);setInput(next[next.length-1].content);setNotice((e as Error).message);}}
  finally{if(attempt===coachAttempt.current)setBusy(false)}
 }
 async function finish(){
  if(!mission||busy)return;endCall();setBusy(true);setNotice('');const attempt=++coachAttempt.current,c=new AbortController();coachAbort.current=c;
  try{let text=feedback;if(!text){text=reviewedReflection(await localCompletion(reflectionMessages(messages),{maxTokens:60,json:true,signal:c.signal}),messages);if(attempt!==coachAttempt.current)return;setFeedback(text);}await record('mission',mission.skill,sessionId,JSON.stringify({title:mission.title,messages,feedback:text}));if(attempt===coachAttempt.current)setSaved(true);}
  catch(e){if(attempt===coachAttempt.current)setNotice((e as Error).message);}
  finally{if(attempt===coachAttempt.current)setBusy(false)}
 }
 async function startCall(){if(!mission)return;if(!ready){setNotice('De AI-coach is nog niet verbonden. De eigenaar moet eerst de AI-koppeling activeren.');return;}setConnecting(true);setNotice('');setSeconds(0);const attempt=++callAttempt.current;try{const s=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true}});if(attempt!==callAttempt.current){s.getTracks().forEach(t=>t.stop());return;}stream.current=s;const p=new RTCPeerConnection();pc.current=p;const a=new Audio();a.autoplay=true;audio.current=a;p.ontrack=e=>{a.srcObject=e.streams[0];a.play().catch(()=>setNotice('Je browser blokkeert geluid. Sta audio toe voor deze site.'))};s.getTracks().forEach(t=>p.addTrack(t,s));const dc=p.createDataChannel('oai-events');dc.onopen=()=>{if(attempt!==callAttempt.current){p.close();return;}for(const message of messages.slice(-20)){dc.send(JSON.stringify({type:'conversation.item.create',item:{type:'message',role:message.role,content:[{type:message.role==='user'?'input_text':'output_text',text:message.content}]}}));}setConnecting(false);setCalling(true);setCallStatus(coachText('Pip luistert…'));dc.send(JSON.stringify({type:'response.create',response:{instructions:'Vervolg het bestaande gesprek. Stel één korte vraag en wacht dan op de leerling.'}}))};dc.onmessage=e=>{try{const v=JSON.parse(e.data);if(v.type==='conversation.item.input_audio_transcription.completed'&&v.transcript)setMessages(m=>[...m,{role:'user',content:v.transcript}]);if(v.type==='response.output_audio_transcript.done'&&v.transcript)setMessages(m=>[...m,{role:'assistant',content:v.transcript}]);if(v.type==='input_audio_buffer.speech_started')setCallStatus(coachText('Pip luistert…'));if(v.type==='response.created')setCallStatus(coachText('Pip denkt even na…'));if(v.type==='output_audio_buffer.started')setCallStatus(coachText('Pip vertelt…'));if(v.type==='response.done')setCallStatus('Jij bent aan de beurt');if(v.type==='error')setNotice('Er ging iets mis in het gesprek. Hang op en probeer opnieuw.');}catch{}};p.onconnectionstatechange=()=>{if(p.connectionState==='failed'||p.connectionState==='disconnected'){endCall();setNotice('De verbinding is verbroken. Je kunt opnieuw bellen.')}};const offer=await p.createOffer();await p.setLocalDescription(offer);const r=await fetch('/api/realtime',{method:'POST',signal:AbortSignal.timeout(35000),headers:{'Content-Type':'application/json'},body:JSON.stringify({sdp:offer.sdp,mission:mission.id,level})});if(!r.ok){const d=await r.json() as any;throw new Error(d.error)}const answer=await r.text();if(attempt!==callAttempt.current){p.close();return;}await p.setRemoteDescription({type:'answer',sdp:answer});}catch(e){if(attempt!==callAttempt.current)return;endCall();setNotice((e as Error).name==='NotAllowedError'?'Geef toegang tot je microfoon om te kunnen praten.':(e as Error).message)}}
 function openGame(name:string){setGame(name);setGameId(crypto.randomUUID());setQ(0);setAnswer(null);setScore(0);setQuizDone(false);setQuizSkills([]);setSelected([]);setFound([]);setGameSaved(false);setNotice('');}
 async function saveGame(kind:string){try{await record(kind,kind==='quiz'?(quizSkills[0]||'Schooltaal'):'Woordenschat',gameId,kind==='quiz'?`${score}/${questions.length} goed; geoefend: ${quizSkills.join(', ')}`:'Vijf woorden gevonden');setGameSaved(true);}catch(e){setNotice((e as Error).message);}}
 function selectCell(i:number){let next=selected.includes(i)?selected.filter(n=>n!==i):[...selected,i];const hit=Object.entries(locations).find(([w,a])=>!found.includes(w)&&a.length===next.length&&a.every(n=>next.includes(n)));if(hit){setFound([...found,hit[0]]);next=[];}setSelected(next);}
 async function saveLesson(status:string){if(!editor)return;setBusy(true);setNotice('');try{await request('/api/state',{type:'lesson',...editor,status});await reload();setEditor(null);setNotice(status==='published'?'Je les is gepubliceerd in jouw lesoverzicht.':'Concept opgeslagen.');}catch(e){setNotice((e as Error).message)}finally{setBusy(false)}}
 async function generateLesson(){if(!editor)return;setGenerating(true);setNotice('');try{const d={text:await localCompletion([{role:'system',content:'Maak een korte NT2-conceptles in het Nederlands. Geef een leerdoel, woordenschat, oefenopdracht en reflectievraag. Publiceer niets.'},{role:'user',content:JSON.stringify({level,topic:editor.title||editor.module})}],{maxTokens:650})};setEditor({...editor,body:d.text,status:'draft'});}catch(e){setNotice((e as Error).message)}finally{setGenerating(false)}}
 const xp=activities.reduce((s,a)=>s+a.xp,0),levelNum=1+Math.floor(xp/200),today=new Date().toLocaleDateString('sv-SE',{timeZone:'Europe/Amsterdam'});
 const dates=[...new Set(activities.map(a=>new Date(a.date).toLocaleDateString('sv-SE',{timeZone:'Europe/Amsterdam'})))];let streak=0;const now=new Date();for(let i=0;i<366;i++){const d=new Date(now);d.setDate(d.getDate()-i);const key=d.toLocaleDateString('sv-SE',{timeZone:'Europe/Amsterdam'});if(dates.includes(key))streak++;else if(i!==0)break;}
 const todayXP=activities.filter(a=>new Date(a.date).toLocaleDateString('sv-SE',{timeZone:'Europe/Amsterdam'})===today).reduce((s,a)=>s+a.xp,0);
 const go=(v:string)=>{if(v.startsWith('teacher')&&role!=='teacher_admin')return;setView(v);setNotice('');if(v==='exercises'){setExerciseCategory('all');setExerciseFocus(undefined)}};
 const openExercises=(c:Category|'all')=>{setExerciseFocus(undefined);setExerciseCategory(c);setView('exercises');setNotice('')};
 const openLearning=(destination:LearningDestination,focus?:Focus)=>{if(destination==='grammar'){setExerciseCategory('grammatica');setExerciseFocus(exercises.some(e=>e.focus===focus)?focus:undefined);setView('exercises')}else go(destination);};
 const learningRefresh=()=>{void reload();void learning.load()};
 function MissionCard({m,index}:{m:Mission;index:number}){const Icon=iconFor(m);return <button className={`mission-card ${m.color}`} style={{animationDelay:`${index*65}ms`}} onClick={()=>startMission(m)}><B><div className="mission-top"><span className="mission-icon"><B><Icon size={24}/></B></span><span className="tag"><B>{m.level}</B></span></div><span className="eyebrow"><B>{m.category}</B></span><h3><B>{m.title}</B></h3><p><B>{m.description}</B></p><div className="mission-meta"><span><B><Clock size={14}/>{m.time} min</B></span><span><B><Sparkles size={14}/>50 XP</B></span><span className="round-chevron"><B><ChevronRight size={17}/></B></span></div></B></button>}
 return <SidebarProvider className="app-shell" style={{'--sidebar-width':'242px'} as React.CSSProperties}>
 <CloseMobileNavigation view={view} settings={settings||appearance||levelCheck}/><Sidebar className="main-sidebar"><SidebarHeader><a href="#" onClick={e=>{e.preventDefault();go('home')}} className="brand"><B><span className="brand-mark"><B><MessageCircle size={24}/></B></span><span><B>taalcoach<span className="brand-ai"><B>AI</B></span></B></span></B></a><div className="brand-caption">Kleine stappen. Groot verschil.</div></SidebarHeader><SidebarContent><div className="nav-label">JOUW LEEROMGEVING</div><SidebarMenu>{nav.map(n=><SidebarMenuItem key={n.id}><SidebarMenuButton isActive={view===n.id} onClick={()=>go(n.id)} className="nav-button"><n.icon size={19}/><span><B>{n.label}</B></span>{view===n.id&&<span className="active-dot"/>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu>{role==='teacher_admin'&&<><div className="sidebar-separator"/><div className="nav-label">VOOR DOCENTEN</div><SidebarMenu><SidebarMenuItem><SidebarMenuButton isActive={view==='teacher'} onClick={()=>go('teacher')} className="nav-button"><NotebookPen size={19}/><span>Lessenmaker</span></SidebarMenuButton></SidebarMenuItem><SidebarMenuItem><SidebarMenuButton isActive={view==='teacher-students'} onClick={()=>go('teacher-students')} className="nav-button"><Users size={19}/><span>Studentenbeheer</span></SidebarMenuButton></SidebarMenuItem></SidebarMenu></>}<div className="sidebar-note"><Leaf size={23}/><h4><B>Groei op jouw tempo</B></h4><p><B>Een beetje oefenen is ook vooruitgang.</B></p><span><B>Jouw herfst vol nieuwe woorden</B></span></div></SidebarContent><SidebarFooter><button className="theme-button" onClick={()=>setAppearance(true)}><Palette size={18}/><span><B>Vormgeving</B></span><ChevronRight size={16}/></button><button className="profile" onClick={()=>setSettings(true)}><B><span className="avatar"><B>J</B></span><span><B><b><B>{profile.name||'Jouw leerplek'}</B></b><small><B>{goal} · Niveau {level}</B></small></B></span><Settings size={17}/></B></button></SidebarFooter></Sidebar>
 <main className="workspace"><header className="topbar"><div className="breadcrumb"><SidebarTrigger className="mobile-menu"/><span><B>Jouw leeromgeving</B></span><ChevronRight size={14}/><b><B>{view==='teacher'?'Lessenmaker':view==='teacher-students'?'Studentenbeheer':nav.find(n=>n.id===view)?.label}</B></b></div><div className="top-actions"><LanguageSwitcher/><span className="streak"><B><Flame size={17}/>{streak} <span><B>{streak===1?'dag':'dagen'}</B></span></B></span><span className="xp-chip"><B><Sparkles size={16}/>{xp} XP</B></span><button className="avatar small" aria-label="Instellingen" onClick={()=>setSettings(true)}><B>J</B></button></div></header>
 <div className="page-content">
 {error&&<div className="error-banner" role="alert">{error}<button onClick={reload}><B>Opnieuw proberen</B></button></div>}
 {notice&&!mission&&!editor&&!game&&<div className="notice" role="status">{notice}<button onClick={()=>setNotice('')} aria-label="Melding sluiten"><B><X size={16}/></B></button></div>}
 {view==='home'&&<><div className="page-heading"><div><div className="season-label"><Leaf size={15}/> EEN NIEUW SEIZOEN OM TE GROEIEN</div><h1><B>{profile.name?`Fijn dat je er bent, ${profile.name}`:'Fijn dat je er bent'}<span className="heading-dot"><B>.</B></span></B></h1><p><B>Maak het jezelf comfortabel. Wat wil je vandaag oefenen?</B></p></div><button className="level-button" onClick={()=>setSettings(true)}><B><GraduationCap size={18}/>Niveau {level}<ChevronRight size={15}/></B></button></div>
 <JourneyHomeCard store={learning} profile={profile} onOpen={()=>go('journey')}/><div className="dashboard-grid"><div className="main-column"><section className="practice-intro"><span className="eyebrow"><NotebookPen size={15}/> JOUW MOMENT OM TE OEFENEN</span><h2>Meer manieren om je Nederlands te laten groeien.</h2><p>Spelling, een goed verhaal of je eigen tekst: kies waar je vandaag zin in hebt.</p><button className="primary-button" onClick={()=>openExercises('all')}>Bekijk alle oefeningen <ChevronRight size={17}/></button><span className="practice-count">{exercises.length} oefeningen · 6 vaardigheden · A1–B2</span></section>
 <div className="section-heading"><div><h2>Kies jouw vaardigheid</h2><p>Vaste opdrachten, heldere uitleg en ruimte om te herhalen.</p></div></div><ExerciseRoutes onChoose={openExercises}/>
 <section className="coach-secondary"><PipMascot/><div><span className="eyebrow">OOK IN JE LEEROMGEVING</span><h3>{coachText("Dit is Pip, je taalmaatje.")}</h3><p>Een taalmaatje met geduld voor jouw verhaal. Oefen samen een gesprek.</p><span className={'connection-status '+(localAI.status==='ready'?'connected':'')}>{localAI.status==='ready'?coachText('Pip is klaar voor je'):coachText('Pip werkt zonder API-sleutel')}</span></div><button className="outline-button" onClick={()=>go('missions')}>{coachText("Ontmoet Pip ")}<ChevronRight size={16}/></button></section>
 <section className="relax-banner"><span className="relax-icon"><B><Coffee size={28}/></B></span><div><span className="eyebrow"><B>EVEN IETS ANDERS</B></span><h3><B>Ook ontspannen is leren.</B></h3><p><B>Duik in een verhaal of speel met nieuwe woorden.</B></p></div><button className="outline-button" onClick={()=>go('content')}><B>Ontdek de leeshoek<ChevronRight size={16}/></B></button></section></div>
 <aside className="right-column"><section className="daily-card"><div className="card-title"><h3><B>Jouw dagelijkse groei</B></h3><span className="icon-tile"><B><SproutIcon/></B></span></div><div className="goal-ring" style={{'--progress':`${Math.min(100,todayXP/50*100)}%`} as React.CSSProperties}><div><span><B>{todayXP}<small><B>/ 50</B></small></B></span><p><B>XP vandaag</B></p></div></div><p className="daily-caption"><B>{todayXP>=50?'Je dagdoel is behaald. Lekker bezig!':'Elke oefening brengt je een stap verder.'}</B></p><div className="week-row">{['M','D','W','D','V','Z','Z'].map((day,i)=>{const d=new Date();d.setDate(d.getDate()-((d.getDay()+6)%7)+i);const key=d.toLocaleDateString('sv-SE',{timeZone:'Europe/Amsterdam'});return <div key={i}><span><B>{day}</B></span><i className={dates.includes(key)?'complete':key===today?'current':''}>{dates.includes(key)?<Check size={13}/>:<span/>}</i></div>})}</div><div className="daily-bottom"><Flame size={17}/>{streak===0?'Jouw eerste stap begint vandaag':`${streak} ${streak===1?'dag':'dagen'} op rij. Houd het vast!`}</div></section>
 <section className="word-card"><span className="eyebrow"><B><BookMarked size={14}/> WOORD VAN VANDAAG</B></span><span className="word-article"><B>het</B></span><h2><B>vertrouwen</B></h2><p><B>Het gevoel dat je op iemand of jezelf kunt rekenen.</B></p><blockquote>“Door te oefenen krijg ik meer vertrouwen.”</blockquote><button className="text-button" onClick={()=>setWord('vertrouwen')}><B>Ontdek dit woord <Plus size={16}/></B></button></section>
 <div className="gentle-note"><Leaf size={18}/><p><B>Je hoeft het niet perfect te zeggen.<br/><b><B>Begin met één kleine oefening.</B></b></B></p></div></aside></div></>}
 {['journey','atelier'].includes(view)&&learning.loaded&&learning.error&&<div className="error-banner" role="alert">{learning.error}<button onClick={learning.load}>Opnieuw proberen</button></div>}
 {['journey','atelier'].includes(view)&&!learning.loaded&&<section className="panel"><p role="status">{learning.error||'Je leerroute laden…'}</p>{learning.error&&<button className="outline-button" onClick={learning.load}>Opnieuw proberen</button>}</section>}
 {view==='journey'&&learning.loaded&&<LearningJourney store={learning} profile={profile} level={level} onCheck={()=>setLevelCheck(true)} onOpen={openLearning}/>}
 {view==='atelier'&&learning.loaded&&<LanguageAtelier store={learning} profile={profile} level={level} onComplete={learningRefresh} seed={readingSeed} onSeedUsed={clearReadingSeed}/>}
 {view==='exercises'&&<ExerciseLibrary initialCategory={exerciseCategory} initialFocus={exerciseFocus} recommendedLevel={level} onComplete={learningRefresh}/>}
 {view==='missions'&&<><section className="pip-introduction"><PipMascot size="large"/><div><span className="eyebrow"><B>JE AI-TAALMAATJE</B></span><h1><B>{coachText("Hoi, ik ben Pip.")}</B></h1><p><B>{coachCharacter(coach).greeting} We oefenen rustig en proberen gewoon opnieuw als iets lastig is.</B></p><div className="pip-traits"><span><B>Geduldig</B></span><span><B>Nieuwsgierig</B></span><span><B>Een beetje eigenwijs</B></span></div><button className="primary-button" onClick={()=>startMission(missions[0])}><MessageCircle size={18}/><B>{coachText("Even kletsen met Pip")}</B></button><PersonalizeCoachButton/></div></section><div className="page-heading"><div><div className="season-label"><Compass size={15}/> LEREN DOOR TE DOEN</div><h1><B>Wat gaan we samen oefenen?</B></h1><p><B>Kies een gesprekssituatie. Je coach helpt je bij praten, typen en terugblikken.</B></p></div><Picker value={level} onChange={setLevel} items={['A1','A2','B1','B2','C1']}/></div><Tabs value={category} onValueChange={setCategory}><TabsList className="filter-tabs">{['Alles','School & studie','Stage & werk','Dagelijks leven'].map(c=><TabsTrigger value={c} key={c}>{c}</TabsTrigger>)}</TabsList></Tabs><div className="mission-grid all-missions">{missions.filter(m=>category==='Alles'||m.category===category).map((m,i)=><MissionCard key={m.id} m={m} index={i}/>)}</div><div className="info-note"><Lightbulb size={18}/>De aangegeven niveaus zijn een richtlijn. Je coach past het gesprek aan jouw gekozen niveau aan.</div></>}
 {view==='content'&&<><NewsPanel field={profile.field} onPractice={article=>{setReadingSeed(article);go('atelier')}}/><div className="page-heading"><div><div className="season-label"><Coffee size={15}/> RUIMTE VOOR NIEUWSGIERIGHEID</div><h1><B>De leeshoek.</B></h1><p><B>Nieuwe woorden ontdekken, even spelen en ontspannen.</B></p></div><Picker value={field} onChange={setField} items={['Alles',...articles.map(a=>a.field)]}/></div><div className="section-heading"><div><h2><B>Een klein verhaal, nieuwe woorden</B></h2><p><B>Leesteksten voor je studie en werk · met klikbare woordhulp</B></p></div></div><div className="article-grid">{articles.map((a,i)=>(field==='Alles'||field===a.field)&&<button key={a.title} className={`article-card article-${i}`} onClick={()=>{setArticle(i);setNotice('')}}><B><div className="article-art"><a.icon size={42}/><span className="reading-label"><B>LEESTEKST · {a.time} MIN</B></span></div><div className="article-body"><span className="eyebrow"><B>{a.field}</B></span><h3><B>{a.title}</B></h3><p><B>{a.text.slice(0,95)}…</B></p><span className="text-button"><B>Lees het verhaal <ChevronRight size={16}/></B></span></div></B></button>)}</div><div className="section-heading"><div><h2><B>Spelen met taal</B></h2><p><B>Een korte pauze waar je iets van opsteekt.</B></p></div></div>{lessons.some(l=>l.status==='published')&&<section className="published-lessons"><h2><B>Jouw lessen</B></h2><div className="lesson-grid">{lessons.filter(l=>l.status==='published').map(l=><button key={l.id} className="panel lesson-card" onClick={()=>setReadLesson(l)}><B><span className="eyebrow"><B>{l.module}</B></span><h3><B>{l.title}</B></h3><span className="text-button"><B>Open les <BookOpen size={15}/></B></span></B></button>)}</div></section>}<div className="games-grid"><button className="game-card quiz-card" onClick={()=>openGame('quiz')}><B><span className="game-symbol"><B><Sparkles size={32}/></B></span><div><span className="eyebrow"><B>5 VRAGEN · 20 XP</B></span><h3><B>De taalquiz</B></h3><p><B>Test je taalgevoel. Klaar voor een uitdaging?</B></p></div><Play size={25}/></B></button><button className="game-card" onClick={()=>openGame('wordsearch')}><B><span className="game-symbol"><B><Search size={32}/></B></span><div><span className="eyebrow"><B>5 WOORDEN · 20 XP</B></span><h3><B>Woordzoeker</B></h3><p><B>Vind de schoolwoorden tussen de letters.</B></p></div><Play size={25}/></B></button></div></>}
 {view==='games'&&<><div className="page-heading"><div><div className="season-label"><Trophy size={15}/> SPEEL MET TAAL</div><h1><B>{coachText("Welkom in de speelhal van Pip.")}</B></h1><p><B>Vang woorden, kraak een kluis of daag je geheugen uit. Kies een spel en begin.</B></p></div></div><ArcadeGames onComplete={reload}/><div className="section-heading"><h2>Meer taaluitdagingen</h2></div><ChallengeGames onComplete={reload}/><div className="section-heading"><h2><B>Even opwarmen</B></h2></div><div className="games-grid"><button className="game-card" onClick={()=>openGame('quiz')}><B><Sparkles/><div><h3><B>De taalquiz</B></h3><p><B>Vijf vragen over de basis van het Nederlands.</B></p></div></B></button><button className="game-card" onClick={()=>openGame('wordsearch')}><B><Search/><div><h3><B>Woordzoeker</B></h3><p><B>Een rustige ronde met schoolwoorden.</B></p></div></B></button></div></>}
 {view==='progress'&&<><div className="page-heading"><div><div className="season-label"><Leaf size={15}/> IEDERE STAP TELT</div><h1><B>Kijk eens hoe je groeit.</B></h1><p><B>Je voortgang op basis van wat je daadwerkelijk oefent.</B></p></div></div><div className="stat-grid"><div><Sparkles/><strong><B>{xp}</B></strong><span><B>verdiende XP</B></span></div><div><Trophy/><strong><B>{levelNum}</B></strong><span><B>jouw speellevel</B></span></div><div><Flame/><strong><B>{streak}</B></strong><span><B>dagen op rij</B></span></div><div><CheckCircle2/><strong><B>{activities.length}</B></strong><span><B>afgeronde oefeningen</B></span></div></div><div className="progress-layout"><section className="panel"><div className="section-heading"><h2><B>Jouw skill map</B></h2><span className="tag"><B>Oefenervaring</B></span></div><p className="muted"><B>Elke afgeronde oefening laat je ervaring groeien. Dit is geen taalexamen of niveaubeoordeling.</B></p><div className="skill-map">{skills.map((s,i)=>{const n=activities.filter(a=>a.skill===s||(a.kind==='quiz'&&a.detail.includes(s))).length;return <div className="skill-row" key={s}><span className={`skill-node node-${i}`}><B><CheckCircle2 size={21}/></B></span><div><div className="skill-label"><b><B>{s}</B></b><span><B>{n} keer geoefend</B></span></div><Progress value={Math.min(n*10,100)}/></div></div>})}</div></section><section className="panel"><Trophy className="large-icon"/><h2><B>Speellevel {levelNum}</B></h2><p><B>{200-xp%200} XP tot je volgende level</B></p><Progress value={xp%200/2}/><h3 className="badge-heading"><B>Jouw mijlpalen</B></h3>{[{t:'De eerste stap',check:activities.length>=1,desc:'Rond je eerste oefening af'},{t:'In gesprek',check:activities.some(a=>a.kind==='mission'),desc:'Voltooi een mission'},{t:'Vaste prik',check:streak>=3,desc:'Oefen 3 dagen op rij'}].map(b=><div className={'achievement '+(b.check?'earned':'')} key={b.t}><span><B><Trophy size={19}/></B></span><div><b><B>{b.t}</B></b><small><B>{b.desc}</B></small></div>{b.check&&<Check size={18}/>}</div>)}</section></div><section className="panel history"><h2><B>Je laatste stappen</B></h2>{activities.length===0?<div className="empty-state"><Compass size={30}/><h3><B>Hier begint jouw verhaal.</B></h3><p><B>Rond een oefening af en zie hier je voortgang.</B></p><button className="primary-button" onClick={()=>openExercises('all')}><B>Kies een oefening</B></button></div>:activities.slice(0,12).map(a=><div className="history-row" key={a.id}><CheckCircle2 size={19}/><div><b><B>{a.kind==='atelier'?exerciseTitle(a.detail):a.kind==='exercise'?exerciseTitle(a.detail):a.kind==='mission'?'Gesprek afgerond':a.kind==='quiz'?'Taalquiz':a.kind==='reading'?'Leestekst gelezen':a.kind==='sentence'?'Zinsarchitect':a.kind==='editor'?'De eindredacteur':a.kind==='register'?'Zeg het tactisch':'Woordzoeker'}</B></b><small><B>{a.skill} · {new Date(a.date).toLocaleDateString('nl-NL')}</B></small></div><span><B>+{a.xp} XP</B></span></div>)}</section></>}
 {view==='teacher'&&role==='teacher_admin'&&<><div className="page-heading"><div><div className="season-label"><NotebookPen size={15}/> VOOR DOCENTEN</div><h1><B>Maak ruimte voor leren.</B></h1><p><B>Bouw modules en lessen. Jij houdt de regie over wat verschijnt.</B></p></div><button className="primary-button" onClick={()=>{setEditor({id:crypto.randomUUID(),title:'',module:'Algemeen',body:'',status:'draft'});setNotice('')}}><B><Plus size={18}/>Nieuwe les</B></button></div><div className="teacher-intro"><span className="icon-tile"><B><Sparkles size={23}/></B></span><div><h3><B>Jouw expertise, met een beetje hulp van AI.</B></h3><p><B>Laat een concept maken en pas het aan. Een les verschijnt pas wanneer jij op Publiceren klikt.</B></p></div><span className="tag"><B>Altijd eerst een concept</B></span></div>{lessons.length===0?<section className="panel empty-state"><BookOpen size={42}/><h2><B>Jouw eerste module begint met één les.</B></h2><p><B>Voeg een eigen les toe of laat de AI een concept uitwerken.</B></p><button className="outline-button" onClick={()=>setEditor({id:crypto.randomUUID(),title:'',module:'Mijn eerste module',body:'',status:'draft'})}><B><Plus size={17}/>Maak je eerste les</B></button></section>:[...new Set(lessons.map(l=>l.module))].map(mod=><section className="module-section" key={mod}><h2><B><BookOpen size={23}/>{mod}</B></h2><div className="lesson-grid">{lessons.filter(l=>l.module===mod).map(l=><button className="panel lesson-card" key={l.id} onClick={()=>{setEditor(l);setNotice('')}}><B><span className={'tag '+(l.status==='published'?'published':'')}><B>{l.status==='published'?'Gepubliceerd':'Concept'}</B></span><h3><B>{l.title}</B></h3><p><B>{l.body.slice(0,140)}…</B></p><span className="text-button"><B>Les bewerken <NotebookPen size={15}/></B></span></B></button>)}</div></section>)}<div className="info-note"><Clock size={18}/><div><b><B>Periodieke conceptlessen</B></b><p><B>Er is nog geen planning actief. Automatisch concepten maken wordt beschikbaar zodra de AI-koppeling en een planning zijn ingesteld.</B></p></div></div></>}
 {view==='teacher-students'&&role==='teacher_admin'&&<><div className="page-heading"><div><div className="season-label"><Users size={15}/> VOOR DOCENTEN</div><h1><B>Studenten in beeld.</B></h1><p><B>Beheer je klassen, studenten en deelname in één overzicht.</B></p></div></div><TeacherDashboard/></>}
 <footer className="page-footer"><span><B><Leaf size={14}/> Groeien doe je op jouw tempo.</B></span><span className="platform-footer-links"><a href="/welkom">Over AI Taalcoach</a><a href="/signout-with-chatgpt?return_to=%2F" target="_top">Uitloggen</a></span></footer>
 </div></main>
 <Dialog open={!!mission} onOpenChange={o=>{if(!o){endCall();coachAttempt.current++;coachAbort.current?.abort();setBusy(false);setMission(null);setNotice('')}}}><DialogContent className="coach-dialog"><DialogHeader><DialogTitle><B>{mission?.title}</B></DialogTitle><DialogDescription><B>{mission?.role} · Niveau {level} · {mission?.time} minuten · AI-gesprek</B></DialogDescription></DialogHeader>{mission&&<><div className="pip-coach-heading"><PipMascot size="small" mood={feedback?'celebrating':busy?'thinking':calling?(callStatus===coachText('Pip vertelt…')?'speaking':'listening'):voiceMood}/><div><b>{coachText("Pip")}</b><small><B>{feedback?'Kijk eens wat je al kunt.':'Je AI-taalmaatje · fouten maken mag'}</B></small></div></div><div className="mission-goals">{mission.goals.map((g,i)=><span key={g}><B><span><B>{i+1}</B></span>{g}</B></span>)}</div><LocalAISetup/>{calling||connecting?<div className="call-panel"><PipMascot size="large" mood={connecting?'thinking':callStatus===coachText('Pip vertelt…')?'speaking':'listening'}/><h3><B>{connecting?coachText('Pip maakt verbinding…'):callStatus}</B></h3><p><B>{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')} · Je praat met een AI</B></p><div className="call-controls"><button className="outline-button" onClick={()=>{stream.current?.getAudioTracks().forEach(t=>t.enabled=muted);setMuted(!muted)}} disabled={connecting}><B>{muted?<MicOff size={20}/>:<Mic size={20}/>} {muted?'Microfoon aan':'Dempen'}</B></button><button className="hangup" onClick={endCall}><B><PhoneOff size={20}/>Ophangen</B></button></div></div>:ready&&!feedback&&<button className="call-start" onClick={startCall} disabled={busy}><B><span className="icon-tile"><B><Phone size={20}/></B></span><span><B><b><B>Praat alsof je belt</B></b><small><B>{coachText("Een gesproken gesprek met Pip · AI-stem")}</B></small></B></span><Headphones size={23}/></B></button>}
 {feedback?<div className="feedback-panel"><PipMascot mood="celebrating"/><h2><B>Een stapje verder.</B></h2><p className="preserve-lines"><B>{feedback}</B></p><div className="feedback-actions">{saved?<span className="success"><B><Check size={18}/>Opgeslagen · +50 XP</B></span>:<button className="primary-button" disabled={busy} onClick={finish}><B>Voortgang opslaan</B></button>}<button className="outline-button" disabled={!saved} onClick={()=>startMission(missions.find(m=>m.id!==mission.id&&m.skill===mission.skill)||missions[1])}><B>Volgende oefening</B></button></div></div>:<><div className="chat-messages" aria-live="polite">{messages.map((m,i)=><div className={'message '+m.role} key={i}>{m.role==='assistant'&&<PipMascot size="small" decorative/>}<div><small><B>{m.role==='assistant'?coachText('Pip'):'Jij'}</B></small><p><B>{m.content}</B></p></div></div>)}{busy&&<div className="thinking"><PipMascot size="small" mood="thinking" decorative/>{coachText("Pip denkt even na…")}</div>}<div ref={chatEnd}/></div>{!calling&&!connecting&&<form className="chat-input" onSubmit={e=>{e.preventDefault();send()}}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Typ je antwoord. Fouten maken mag…" aria-label="Je antwoord" disabled={busy}/><button type="submit" aria-label="Verstuur antwoord" disabled={busy||!input.trim()||localAI.status!=='ready'}><B><Send size={19}/></B></button></form>}{!calling&&!connecting&&<VoiceControls resetKey={sessionId} reply={[...messages].reverse().find(m=>m.role==='assistant')?.content||''} disabled={busy||localAI.status!=='ready'} onTranscript={text=>void send(text)} onMood={setVoiceMood}/>}<div className="chat-bottom"><span><B><Leaf size={13}/>Neem je tijd. Je bent hier om te leren.</B></span><button className="text-button" onClick={finish} disabled={busy||localAI.status!=='ready'||messages.filter(m=>m.role==='user').length<2}><B>Afronden & terugblik <Check size={15}/></B></button></div></>}{notice&&<div className="notice" role="alert">{notice}</div>}</>}</DialogContent></Dialog>
 <Dialog open={article!==null} onOpenChange={o=>{if(!o){setArticle(null);setNotice('')}}}><DialogContent className="reading-dialog">{article!==null&&<><DialogHeader><span className="eyebrow"><B>{articles[article].field} · LEESTEKST</B></span><DialogTitle><B>{articles[article].title}</B></DialogTitle><DialogDescription><B>Klik op een onderstreept woord voor uitleg.</B></DialogDescription></DialogHeader><p className="reading-text"><B>{language!=='nl'?<T text={articles[article].text}/>:articles[article].text.split(/(\s+)/).map((t,i)=>{const key=t.toLowerCase().replace(/[.,:;!?]/g,'');return dictionary[key]?<button key={i} className="word-link" onClick={()=>setWord(key)}><B>{t}</B></button>:<span key={i}><B>{t}</B></span>})}</B></p><div className="reading-reflect"><Lightbulb size={22}/><div><b><B>Even nadenken</B></b><p><B>Welke tip uit dit verhaal kun jij zelf gebruiken?</B></p></div></div><button className="primary-button" disabled={activities.some(a=>a.id.endsWith('article-'+article))} onClick={async()=>{try{await record('reading','Woordenschat','article-'+article,articles[article].title);setNotice('Goed gelezen! Je hebt 20 XP verdiend.')}catch(e){setNotice((e as Error).message)}}}><B>{activities.some(a=>a.id.endsWith('article-'+article))?<><Check size={18}/>Gelezen · 20 XP verdiend</>:<>Gelezen · ontvang 20 XP</>}</B></button>{notice&&<p role="status"><B>{notice}</B></p>}</>}</DialogContent></Dialog>
 <Dialog open={!!word} onOpenChange={o=>{if(!o)setWord('')}}><DialogContent className="word-dialog"><DialogHeader><DialogDescription><B>WOORDHULP</B></DialogDescription><DialogTitle><B>{dictionary[word]?.article} {word}</B></DialogTitle></DialogHeader><p><B>{dictionary[word]?.meaning}</B></p><div className="word-detail"><span><B>Synoniem</B></span><b><B>{dictionary[word]?.synonym}</B></b></div><div className="word-detail"><span><B>Engels</B></span><b><B>{dictionary[word]?.en}</B></b></div><button className="outline-button" onClick={()=>{if('speechSynthesis' in window){const u=new SpeechSynthesisUtterance(word);u.lang='nl-NL';u.rate=.85;speechSynthesis.cancel();speechSynthesis.speak(u)}}}><B><Volume2 size={17}/>Luister naar de uitspraak</B></button></DialogContent></Dialog>
 <Dialog open={!!game} onOpenChange={o=>{if(!o){setGame(null);setNotice('')}}}><DialogContent className="game-dialog"><DialogHeader><DialogTitle><B>{game==='quiz'?'De taalquiz':'Woordzoeker'}</B></DialogTitle><DialogDescription><B>{game==='quiz'?'Een beetje uitdaging, een heleboel taalgevoel.':'Klik alle letters van een woord aan. Zoek horizontaal of verticaal.'}</B></DialogDescription></DialogHeader>{game==='quiz'?quizDone?<div className="quiz-result"><Trophy size={48}/><h2><B>{score} van de {questions.length} goed!</B></h2><p><B>Elke vraag is een kans om iets te leren.</B></p><button className="primary-button" disabled={gameSaved} onClick={()=>saveGame('quiz')}><B>{gameSaved?'Opgeslagen · +20 XP':'Resultaat opslaan · 20 XP'}</B></button><button className="text-button" onClick={()=>openGame('quiz')}><B><RotateCcw size={16}/>Nog een ronde</B></button></div>:<><div className="quiz-progress"><span><B>Vraag {q+1} / {questions.length}</B></span><span><B>{score} goed</B></span></div><Progress value={q/questions.length*100}/><h2 className="quiz-question"><B>{questions[q].q}</B></h2><div className="answers">{questions[q].a.map((a,i)=><button key={a} className={(answer!==null?(i===questions[q].correct?'correct ':i===answer?'wrong ':''):'')+'answer answer-'+i} disabled={answer!==null} onClick={()=>{setAnswer(i);if(i===questions[q].correct)setScore(score+1);setQuizSkills([...new Set([...quizSkills,questions[q].skill])]);}}><B><span><B>{String.fromCharCode(65+i)}</B></span>{a}{answer!==null&&i===questions[q].correct&&<Check size={18}/>}</B></button>)}</div>{answer!==null&&<div className="answer-explanation"><p><B>{questions[q].why}</B></p><button className="primary-button" onClick={()=>{if(q===questions.length-1)setQuizDone(true);else{setQ(q+1);setAnswer(null)}}}><B>{q===questions.length-1?'Bekijk resultaat':'Volgende vraag'}</B></button></div>}</>:<><div className="word-grid">{grid.join('').split('').map((c,i)=><button aria-label={`${c}, rij ${Math.floor(i/8)+1}, kolom ${i%8+1}`} key={i} onClick={()=>selectCell(i)} className={(selected.includes(i)?'selected ':'')+(found.some(w=>locations[w].includes(i))?'found':'')}><B>{c}</B></button>)}</div><div className="find-words">{Object.keys(locations).map(w=><span className={found.includes(w)?'done':''} key={w}><B>{found.includes(w)&&<Check size={14}/>} {w}</B></span>)}</div>{found.length===5?<button className="primary-button" disabled={gameSaved} onClick={()=>saveGame('wordsearch')}><B>{gameSaved?'Opgeslagen · +20 XP':'Alles gevonden! Ontvang 20 XP'}</B></button>:<button className="text-button" onClick={()=>setSelected([])}><B><RotateCcw size={15}/>Selectie wissen</B></button>}</>}{notice&&<div className="notice" role="alert">{notice}</div>}</DialogContent></Dialog>
 <Dialog open={!!editor} onOpenChange={o=>{if(!o){setEditor(null);setNotice('')}}}><DialogContent className="editor-dialog"><DialogHeader><DialogTitle><B>{editor?.title||'Een nieuwe les'}</B></DialogTitle><DialogDescription><B>Werk aan je les en publiceer pas als jij tevreden bent.</B></DialogDescription></DialogHeader>{editor&&<><label className="field-label"><B>Lestitel<input value={editor.title} onChange={e=>setEditor({...editor,title:e.target.value})} placeholder="Bijvoorbeeld: kennismaken op stage"/></B></label><div className="editor-row"><label className="field-label"><B>Module<input value={editor.module} onChange={e=>setEditor({...editor,module:e.target.value})}/></B></label><label className="field-label"><B>Niveau<Picker value={level} onChange={setLevel} items={['A1','A2','B1','B2','C1']}/></B></label></div><LocalAISetup/><button className="ai-generate" disabled={generating||!!editor.body.trim()||localAI.status!=='ready'} onClick={generateLesson}><B>{generating?<LoaderCircle size={17} className="spin"/>:<Sparkles size={17}/>}{generating?'Je concept wordt gemaakt…':'Laat AI een eerste concept maken'}</B></button><label className="field-label"><B>Lesinhoud<textarea rows={10} value={editor.body} onChange={e=>setEditor({...editor,body:e.target.value})} placeholder={'Leerdoel\nWat kan de student na deze les?\n\nWoordenschat\n\nOpdracht / roleplay\n\nReflectie'}/></B></label><div className="editor-actions"><button className="outline-button" disabled={busy||!editor.title.trim()||!editor.body.trim()} onClick={()=>saveLesson('draft')}><B>Concept opslaan</B></button><button className="primary-button" disabled={busy||!editor.title.trim()||!editor.body.trim()} onClick={()=>saveLesson('published')}><B><Check size={17}/>Publiceren</B></button></div>{notice&&<p className="notice" role="alert"><B>{notice}</B></p>}</>}</DialogContent></Dialog>
 <Dialog open={!!readLesson} onOpenChange={o=>{if(!o)setReadLesson(null)}}><DialogContent className="reading-dialog"><DialogHeader><DialogDescription><B>{readLesson?.module}</B></DialogDescription><DialogTitle><B>{readLesson?.title}</B></DialogTitle></DialogHeader><div className="preserve-lines">{readLesson?.body}</div></DialogContent></Dialog>
 {levelCheck&&<LevelCheck store={learning} onClose={()=>setLevelCheck(false)}/>}
 <AppearanceDialog open={appearance} onOpenChange={setAppearance}/>
 <Dialog open={settings} onOpenChange={setSettings}><DialogContent className="profile-dialog"><DialogHeader><DialogTitle><B>Jouw profiel</B></DialogTitle><DialogDescription><B>Maak de oefeningen persoonlijk. Je kunt alles later aanpassen.</B></DialogDescription></DialogHeader><LevelSummary store={learning} compact onCheck={()=>{setSettings(false);go('journey');setLevelCheck(true)}}/><ProfileForm profile={{...profile,goal,language}} onSave={p=>{setProfile(p);setLevel(p.adaptive&&learning.data.advice.level?learning.data.advice.level:p.level);setGoal(p.goal);chooseLanguage(p.language);setSettings(false);setNotice('Je profiel is opgeslagen.')}}/></DialogContent></Dialog>
 </SidebarProvider>
}
function SproutIcon(){return <Leaf size={21}/>}

function CloseMobileNavigation({view,settings}:{view:string;settings:boolean}){const {setOpenMobile}=useSidebar();useEffect(()=>{setOpenMobile(false)},[view,settings,setOpenMobile]);return null}

function exerciseTitle(detail:string){try{return JSON.parse(detail).title||'Oefening afgerond'}catch{return 'Oefening afgerond'}}
