import {grammarExercises} from './grammar-exercises';
export type Category='grammatica'|'spelling'|'lezen'|'luisteren'|'schrijven'|'formuleren';
export type Question={prompt:string;options?:string[];correct?:number;accepted?:string[];explanation:string};
export type Exercise={id:string;category:Category;level:'A1'|'A2'|'B1'|'B2';focus?:string;title:string;description:string;minutes:number;passage?:string;audio?:string;questions:Question[];writing?:{prompt:string;minWords:number;maxWords:number;checklist:string[];example:string}};
export const categories:{id:Category;name:string;description:string}[]=[
 {id:'grammatica',name:'Grammatica',description:'Lidwoorden, enkelvoud, meervoud en de drie tijden.'},
 {id:'spelling',name:'Spelling',description:'Werkwoorden, klanken en lastige woorden.'},
 {id:'lezen',name:'Begrijpend lezen',description:'Begrijp de kern, details en bedoeling van een tekst.'},
 {id:'luisteren',name:'Luisteren',description:'Haal informatie uit berichten en mededelingen.'},
 {id:'schrijven',name:'Schrijven',description:'Schrijf een bericht, e-mail of onderbouwde tekst.'},
 {id:'formuleren',name:'Formuleren',description:'Maak je zinnen duidelijk, passend en precies.'}
];
const text=(prompt:string,accepted:string[],explanation:string):Question=>({prompt,accepted,explanation});
const choice=(prompt:string,options:string[],correct:number,explanation:string):Question=>({prompt,options,correct,explanation});
export const exercises:Exercise[]=[
 ...grammarExercises,
 {id:'spelling-a2',category:'spelling',level:'A2',title:'Eén of twee letters?',description:'Vul het ontbrekende woord in. Let op korte en lange klanken.',minutes:5,questions:[
 text('Eén afspraak, twee …',['afspraken'],'Een lange a-klank in een open lettergreep schrijf je met één a: af-spra-ken.'),
 text('Eén les, twee …',['lessen'],'De e blijft kort. Daarom verdubbel je de s: les-sen.'),
 text('Eén probleem, twee …',['problemen'],'In de open lettergreep schrijf je de lange e-klank met één e: pro-ble-men.'),
 text('Eén collega, twee …',["collega's",'collega’s'],'De apostrof voorkomt dat de a als een korte klank wordt gelezen.'),
 text('Eén idee, twee …',['ideeën'],'Het trema geeft aan dat de laatste e een nieuwe lettergreep begint: idee-ën.')
 ]},
 {id:'spelling-b1',category:'spelling',level:'B1',title:'Werkwoorden op je werk',description:'Kies de juiste werkwoordsvorm in een herkenbare situatie.',minutes:5,questions:[
 text('Hij … morgen aan een nieuw project. (werken)',['werkt'],'Bij hij gebruik je in de tegenwoordige tijd de stam + t: werk + t.'),
 text('… jij deze opdracht lastig? (vinden)',['vind'],'Als jij achter de persoonsvorm staat, vervalt de t: vind jij.'),
 text('De docent heeft het antwoord … (controleren)',['gecontroleerd'],'Het voltooid deelwoord van controleren is gecontroleerd.'),
 text('Gisteren … wij de planning. (bespreken)',['bespraken'],'Bespreken is een sterk werkwoord: wij bespraken.'),
 text('De afspraak … naar vrijdag verplaatst. (worden)',['wordt'],'Het onderwerp is enkelvoud: de afspraak wordt. De stam word krijgt een t.')
 ]},
 {id:'spelling-b2',category:'spelling',level:'B2',title:'De laatste taalcontrole',description:'Scherp je spelling aan voor rapporten en zakelijke e-mails.',minutes:6,questions:[
 text('Vul de juiste spelling in: financiele / financiële',['financiële'],'Het trema maakt de lettergreepgrens zichtbaar: fi-nan-ci-ë-le.'),
 text('Vul de juiste spelling in: onmiddelijk / onmiddellijk',['onmiddellijk'],'Onmiddellijk schrijf je met twee d’s en twee l’en.'),
 text('Het team heeft de resultaten … (analyseren)',['geanalyseerd'],'Het voltooid deelwoord is geanalyseerd, met één n.'),
 text('Vul in: Ik ga … dat je op tijd bent. (ervan uit / er vanuit)',['ervan uit'],'De combinatie is ergens van uitgaan: ik ga ervan uit. “Uit” hoort bij het werkwoord.'),
 text('Vul de juiste spelling in: verantwoordelijk / verandwoordelijk',['verantwoordelijk'],'Verantwoordelijk hoort bij verantwoorden en antwoord: met een t vóór woord.')
 ]},
 {id:'lezen-a2',category:'lezen',level:'A2',title:'Een bericht van de bibliotheek',description:'Vind praktische informatie in een kort bericht.',minutes:5,passage:'Vanaf maandag 12 oktober is de bibliotheek op maandagavond open tot 20.00 uur. Op dinsdag tot en met vrijdag sluit de bibliotheek om 18.00 uur. Op zaterdag kun je er terecht van 10.00 tot 14.00 uur. Boeken terugbrengen kan ook buiten openingstijden via de brievenbus naast de ingang. Wil je op maandagavond gebruikmaken van een computer? Reserveer dan vooraf via de website. Boeken lenen hoeft niet op afspraak.',questions:[
 choice('Tot hoe laat is de bibliotheek op maandag open?',['14.00 uur','18.00 uur','20.00 uur'],2,'In de eerste zin staat dat de bibliotheek op maandagavond tot 20.00 uur open is.'),
 choice('Waarvoor moet je vooraf reserveren?',['Een computer op maandagavond','Boeken terugbrengen','Boeken lenen op zaterdag'],0,'Reserveren is nodig voor een computer op maandagavond. Boeken lenen hoeft niet op afspraak.'),
 choice('De bibliotheek is dicht. Kun je toch een boek terugbrengen?',['Nee, alleen tijdens openingstijden.','Ja, via de brievenbus naast de ingang.','Ja, maar alleen op maandag.'],1,'De tekst noemt expliciet dat terugbrengen buiten openingstijden via de brievenbus kan.')
 ]},
 {id:'lezen-b1',category:'lezen',level:'B1',title:'Thuiswerken op proef',description:'Onderscheid voorwaarden, voordelen en afspraken.',minutes:6,passage:'Een stagebedrijf start een proef met thuiswerken. Medewerkers mogen gedurende twee maanden maximaal twee dagen per week thuis werken. Stagiairs kunnen deelnemen als hun begeleider daarmee instemt. De klantenservice blijft iedere werkdag op kantoor bezet. Teams maken daarom onderling een rooster. Het bedrijf verwacht dat medewerkers thuis rustiger kunnen werken aan taken die concentratie vragen. Tegelijk vindt de directie persoonlijk contact belangrijk. Daarom komt ieder team op woensdag samen op kantoor. Na de proef wordt niet alleen naar de productiviteit gekeken, maar ook naar de samenwerking en het welzijn van medewerkers.',questions:[
 choice('Wanneer mag een stagiair deelnemen?',['Altijd, net als elke medewerker.','Als de begeleider toestemming geeft.','Alleen als de stagiair op de klantenservice werkt.'],1,'De begeleider moet instemmen. De regeling is dus niet automatisch voor alle stagiairs van toepassing.'),
 choice('Waarom is woensdag een gezamenlijke kantoordag?',['Om het persoonlijke contact te behouden.','Omdat er op woensdag geen klanten zijn.','Omdat thuiswerken dan technisch onmogelijk is.'],0,'De directie vindt persoonlijk contact belangrijk. De gezamenlijke dag ondersteunt dat.'),
 choice('Wat wordt na twee maanden beoordeeld?',['Alleen hoeveel werk er is gedaan.','Alleen of de klantenservice open is.','Productiviteit, samenwerking en welzijn.'],2,'De laatste zin noemt alle drie de aspecten.')
 ]},
 {id:'lezen-b2',category:'lezen',level:'B2',title:'Meer cijfers, betere besluiten?',description:'Herken een standpunt, nuance en impliciete conclusie.',minutes:8,passage:'Een school wil de kwaliteit van haar onderwijs beter volgen. Voortaan worden toetsresultaten, aanwezigheid en tevredenheid elk kwartaal in een dashboard verzameld. Volgens de schoolleiding kunnen teams daardoor sneller zien waar ondersteuning nodig is. Een docent plaatst een kanttekening: een dalend gemiddelde kan ook ontstaan doordat een toets moeilijker was of doordat een nieuwe groep meer begeleiding nodig heeft. Hij vreest dat één cijfer te snel als oordeel over een docent wordt gebruikt. De schoolleiding erkent dat risico. Zij stelt voor om de gegevens altijd samen met docenten te bespreken en bij opvallende resultaten eerst aanvullende vragen te stellen. Het dashboard moet het begin van een gesprek zijn, niet het einde ervan.',questions:[
 choice('Wat is de kern van de kritiek van de docent?',['Alle gegevens zijn onbetrouwbaar.','Cijfers kunnen zonder context verkeerd worden geïnterpreteerd.','Toetsen moeten worden afgeschaft.'],1,'De docent noemt meerdere mogelijke verklaringen voor een dalend gemiddelde. Hij wijst op ontbrekende context.'),
 choice('Welke conclusie past het best bij de laatste zin?',['Cijfers moeten aanleiding geven tot nader onderzoek.','Teams mogen nooit conclusies trekken.','Een dashboard vervangt het gesprek met docenten.'],0,'Het dashboard dient als vertrekpunt voor vragen en gesprekken; het levert niet automatisch het definitieve oordeel.'),
 choice('Hoe reageert de schoolleiding op de kritiek?',['Zij verwerpt de kritiek volledig.','Zij stopt met het verzamelen van gegevens.','Zij erkent het risico en past de werkwijze aan.'],2,'De leiding erkent het risico en wil cijfers samen met docenten bespreken.')
 ]},
 {id:'luisteren-a2',category:'luisteren',level:'A2',title:'Een gewijzigde afspraak',description:'Luister naar een voicemail en onthoud de belangrijkste gegevens.',minutes:5,audio:'/audio/afspraak.mp3',passage:'Goedemorgen, u spreekt met de praktijk van dokter Van Dijk. Uw afspraak van donderdag kan helaas niet doorgaan, omdat de dokter die ochtend een spoedgeval heeft. We hebben een nieuwe afspraak voor u op vrijdag om half elf. Wilt u tien minuten eerder komen en uw identiteitsbewijs meenemen? Als vrijdag niet lukt, bel ons dan vandaag vóór vier uur terug. U hoeft niet terug te bellen als u op vrijdag kunt komen. Tot ziens.',questions:[
 choice('Wanneer is de nieuwe afspraak?',['Donderdag om 10.30 uur.','Vrijdag om 10.30 uur.','Vrijdag om 11.30 uur.'],1,'Half elf betekent 10.30 uur. De nieuwe afspraak is op vrijdag.'),
 choice('Hoe laat moet je aanwezig zijn?',['10.20 uur.','10.30 uur.','10.40 uur.'],0,'Je moet tien minuten vóór half elf komen: om 10.20 uur.'),
 choice('Wanneer moet je terugbellen?',['Altijd, om de afspraak te bevestigen.','Alleen als je geen identiteitsbewijs hebt.','Als je vrijdag niet kunt komen.'],2,'Je hoeft niet terug te bellen als vrijdag lukt. Anders moet je vandaag vóór vier uur bellen.')
 ]},
 {id:'luisteren-b1',category:'luisteren',level:'B1',title:'Mededelingen over een project',description:'Onderscheid wat er verandert en wat hetzelfde blijft.',minutes:6,audio:'/audio/overleg.mp3',passage:'Goedemorgen allemaal. Ik heb drie mededelingen over ons project. Ten eerste: de presentatie is verplaatst van dinsdag naar donderdag. De locatie blijft hetzelfde: lokaal twee punt veertien. Ten tweede: lever je eigen onderdeel uiterlijk maandag om twaalf uur in. Dan heeft Noor voldoende tijd om alle onderdelen samen te voegen. Ten derde: als je hulp nodig hebt met de grafieken, kun je vrijdag na de les bij mij langskomen. Stuur me vooraf even een bericht, zodat ik weet hoeveel studenten er komen. De deadline voor het inleveren verandert dus niet, ook al is de presentatie later.',questions:[
 choice('Wat is veranderd?',['De dag van de presentatie.','De locatie van de presentatie.','De inleverdeadline.'],0,'De presentatie gaat van dinsdag naar donderdag. De locatie en deadline blijven gelijk.'),
 choice('Waarom moet je je onderdeel maandag inleveren?',['De presentatie is op maandagmiddag.','Noor moet de onderdelen nog samenvoegen.','De docent is de rest van de week afwezig.'],1,'Noor heeft tijd nodig om alles samen te voegen vóór de presentatie.'),
 choice('Wat doe je als je vrijdag hulp met grafieken wilt?',['Je gaat zonder bericht langs vóór de les.','Je wacht tot de volgende presentatie.','Je stuurt vooraf een bericht en komt na de les.'],2,'De docent vraagt om vooraf een bericht te sturen en noemt vrijdag na de les.')
 ]},
 {id:'luisteren-b2',category:'luisteren',level:'B2',title:'Een autovrije zaterdag',description:'Luister naar voorwaarden, uitzonderingen en verschillende standpunten.',minutes:8,audio:'/audio/buurt.mp3',passage:"Volgende maand begint in onze wijk een proef met een autovrije zaterdag. De gemeente wil onderzoeken of bewoners meer gebruik gaan maken van de openbare ruimte. Tijdens de proef blijven de hoofdwegen bereikbaar. Alleen de twee straten rondom het plein zijn tussen tien uur 's ochtends en zes uur 's avonds afgesloten voor auto's. Fietsers mogen wel doorrijden, maar moeten bij het plein afstappen. Bewoners met een gehandicaptenparkeerkaart kunnen vooraf een uitzondering aanvragen. Ondernemers zijn verdeeld over het plan. Sommigen verwachten extra bezoekers, terwijl anderen zich zorgen maken over de bevoorrading. De gemeente verzamelt na elke zaterdag ervaringen. Pas na vier proefdagen besluit de gemeenteraad of de regeling wordt voortgezet.",questions:[
 choice('Welk gebied wordt afgesloten voor auto’s?',['De hele wijk, de hele dag.','Twee straten rond het plein tussen 10.00 en 18.00 uur.','Alleen de hoofdwegen.'],1,'De hoofdwegen blijven bereikbaar. Het gaat om twee straten rond het plein en om vaste tijden.'),
 choice('Wat betekent dat ondernemers “verdeeld” zijn?',['Ze zijn het onderling niet eens over het plan.','Ze moeten allemaal naar een andere wijk verhuizen.','Ze hebben samen één positief standpunt.'],0,'Sommigen zien kansen, anderen maken zich zorgen. Er bestaan verschillende standpunten.'),
 choice('Wanneer valt het besluit over voortzetting?',['Vóór de eerste proefdag.','Automatisch na iedere zaterdag.','Na vier proefdagen en het verzamelen van ervaringen.'],2,'De gemeenteraad neemt pas na vier proefdagen een besluit.')
 ]},
 {id:'schrijven-a2',category:'schrijven',level:'A2',title:'Een afspraak verzetten',description:'Schrijf een kort, duidelijk bericht met een alternatief.',minutes:10,questions:[],writing:{prompt:'Je hebt dinsdag om 14.00 uur een afspraak met je mentor. Je moet op dat moment werken. Schrijf een bericht: leg uit waarom je niet kunt, stel donderdag om 10.00 uur voor en vraag of dat past.',minWords:35,maxWords:80,checklist:['Ik heb een passende begroeting en afsluiting gebruikt.','Ik heb uitgelegd waarom dinsdag niet lukt.','Ik heb donderdag om 10.00 uur voorgesteld en een vraag gesteld.','Ik heb hoofdletters, punten en werkwoorden nagekeken.'],example:'Beste mevrouw De Vries,\n\nDinsdag om 14.00 uur hebben we een afspraak. Helaas moet ik dan werken. Kunnen we onze afspraak verzetten naar donderdag om 10.00 uur? Ik hoor graag of dat voor u uitkomt.\n\nMet vriendelijke groet,\nSam'}},
 {id:'schrijven-b1',category:'schrijven',level:'B1',title:'Een zakelijke klacht',description:'Leg een probleem uit en vraag op een vriendelijke manier om een oplossing.',minutes:15,questions:[],writing:{prompt:'Je hebt een laptop besteld voor je opleiding. Het apparaat is geleverd, maar de batterij laadt niet op. Schrijf een e-mail aan de klantenservice. Beschrijf het probleem, vertel wat je al hebt geprobeerd, leg uit waarom je de laptop nodig hebt en vraag om een concrete oplossing.',minWords:80,maxWords:150,checklist:['Mijn lezer weet direct waarom ik schrijf.','Ik heb het probleem en mijn eerdere poging concreet beschreven.','Ik heb een haalbare oplossing of vervolgstap gevraagd.','Ik heb mijn tekst verdeeld in logische alinea’s.','Mijn toon blijft vriendelijk en mijn zinnen zijn nagekeken.'],example:'Geachte klantenservice,\n\nVorige week heb ik bij u een laptop besteld voor mijn opleiding. Het apparaat is gisteren geleverd, maar de batterij laadt niet op. Ook na twee uur aan de oplader blijft het percentage op nul staan.\n\nIk heb gecontroleerd of de kabel goed is aangesloten en een ander stopcontact geprobeerd. Helaas heeft dat niet geholpen. Ik heb de laptop volgende week nodig om aan een project te werken.\n\nKunt u aangeven hoe dit probleem kan worden opgelost? Als reparatie lang duurt, ontvang ik graag een vervangend apparaat. Ik stuur het bestelnummer en een foto mee.\n\nMet vriendelijke groet,\nSam'}},
 {id:'schrijven-b2',category:'schrijven',level:'B2',title:'Een onderbouwd voorstel',description:'Werk een standpunt uit, bespreek een bezwaar en eindig met een voorstel.',minutes:20,questions:[],writing:{prompt:'Je opleiding overweegt om één lesdag per week online te geven. Schrijf een advies aan de opleidingscoördinator. Neem een standpunt in, geef twee argumenten, bespreek één mogelijk bezwaar en stel een concrete proef voor.',minWords:140,maxWords:230,checklist:['Mijn standpunt is duidelijk en blijft consistent.','Ik heb twee verschillende argumenten uitgewerkt met voorbeelden.','Ik heb een serieus bezwaar besproken en erop gereageerd.','Mijn voorstel is concreet en uitvoerbaar.','Ik heb verbindingswoorden en logische alinea’s gebruikt.','Ik heb mijn tekst nagekeken op herhaling, spelling en zinsbouw.'],example:'Beste opleidingscoördinator,\n\nIk stel voor om één online lesdag per week gedurende twee maanden uit te proberen. Dat kan voordelen hebben, mits de online lessen zorgvuldig worden ingericht.\n\nTen eerste besparen studenten reistijd. Die tijd kunnen zij gebruiken om opdrachten voor te bereiden. Vooral studenten die ver van school wonen, profiteren daarvan. Ten tweede kunnen opgenomen uitleg en digitaal lesmateriaal helpen bij het herhalen van moeilijke onderwerpen. Studenten kunnen dan op hun eigen tempo terugkijken.\n\nEen mogelijk bezwaar is dat het onderlinge contact afneemt. Dat risico verdient aandacht. Daarom zou ik de online dag vooral gebruiken voor individuele opdrachten en theoretische uitleg. Praktijklessen en groepswerk blijven op school. Ook kan ieder team online een kort vast overlegmoment houden.\n\nMijn voorstel is om met één klas te beginnen en na twee maanden zowel studenten als docenten te bevragen. Kijk daarbij naar resultaten, werkdruk en samenwerking. Op basis van die ervaringen kan de opleiding besluiten of uitbreiding verstandig is.\n\nMet vriendelijke groet,\nSam'}},
 {id:'formuleren-a2',category:'formuleren',level:'A2',title:'Duidelijk en vriendelijk',description:'Kies een zin die past bij wat je wilt zeggen.',minutes:5,questions:[
 choice('Je begrijpt een uitleg niet. Wat zeg je?',['Praat normaal.','Kunt u dat nog een keer uitleggen?','Ik wil dat niet.'],1,'Je vraagt vriendelijk en duidelijk om een herhaling.'),
 choice('Maak het verzoek beleefder: “Geef mij de planning.”',['Zou je mij de planning kunnen sturen?','Jij moet mij de planning geven.','Planning nu.'],0,'“Zou je … kunnen” maakt van een bevel een beleefd verzoek.'),
 choice('Welke zin heeft de juiste woordvolgorde?',['Morgen ik begin om negen uur.','Morgen begin ik om negen uur.','Morgen om negen ik begin uur.'],1,'Na “morgen” volgt de persoonsvorm “begin”, daarna “ik”.')
 ]},
 {id:'formuleren-b1',category:'formuleren',level:'B1',title:'Verbind je gedachten',description:'Gebruik oorzaak, tegenstelling en gevolg op de juiste manier.',minutes:6,questions:[
 choice('Welke zin geeft een oorzaak correct weer?',['Ik ben later, omdat de trein vertraging heeft.','Ik ben later, omdat de trein heeft vertraging.','Omdat ik ben later, de trein vertraging.'],0,'Na “omdat” staat de persoonsvorm achteraan in de bijzin: de trein vertraging heeft.'),
 choice('Je bent moe, maar wilt toch naar de les. Welke zin past?',['Ik ben moe, daarom ga ik niet.','Hoewel ik moe ben, ga ik naar de les.','Omdat ik naar de les ga, ben ik altijd moe.'],1,'“Hoewel” drukt een tegenstelling uit: ondanks de vermoeidheid ga je naar de les.'),
 choice('Welke formulering is het meest concreet?',['Ik doe het later.','Dat komt wel goed.','Ik stuur je het verslag morgen vóór 12.00 uur.'],2,'Een duidelijke handeling en een precies tijdstip voorkomen misverstanden.')
 ]},
 {id:'formuleren-b2',category:'formuleren',level:'B2',title:'Precies en genuanceerd',description:'Maak stevige uitspraken zorgvuldig en helder.',minutes:7,questions:[
 choice('Herschrijf genuanceerd: “Online lessen zijn altijd slechter.”',['Online lessen kunnen minder geschikt zijn voor praktijkopdrachten die directe begeleiding vragen.','Online lessen zijn gewoon waardeloos.','Niemand leert ooit iets online.'],0,'De zin benoemt een concrete situatie en vermijdt een ongefundeerde absolute uitspraak.'),
 choice('Welke zin is het duidelijkst?',['Ten aanzien van de uitvoering van de implementatie is sprake van vertraging.','We voeren het nieuwe systeem twee weken later in.','Het een en ander loopt anders.'],1,'De zin noemt wie iets doet, wat er gebeurt en hoe groot de vertraging is.'),
 choice('Je wilt een bezwaar erkennen én je voorstel behouden. Welke zin past?',['Uw bezwaar is onbelangrijk.','U heeft misschien iets gezegd, maar ik luister niet.','Ik begrijp dat extra overleg tijd kost. Toch kan een kort wekelijks overleg dubbel werk voorkomen.'],2,'Je erkent het bezwaar en geeft vervolgens een inhoudelijk argument voor je voorstel.')
 ]}
];
export const normalizeAnswer=(s:string)=>s.normalize('NFC').trim().toLocaleLowerCase('nl').replace(/[’‘]/g,"'").replace(/\s+/g,' ').replace(/[.!?]+$/,'');
export function isCorrect(q:Question,answer:string){return q.options?answer===String(q.correct):(q.accepted||[]).some(s=>normalizeAnswer(s)===normalizeAnswer(answer));}
export const wordCount=(s:string)=>s.trim()?s.trim().split(/\s+/).length:0;
export type ExerciseData={answers:string[];text:string;checks:boolean[];assisted?:boolean};
export function canComplete(ex:Exercise,d:ExerciseData){return ex.writing?wordCount(d.text)>=ex.writing.minWords&&wordCount(d.text)<=ex.writing.maxWords&&ex.writing.checklist.every((_,i)=>d.checks[i]===true):ex.questions.every((_,i)=>!!d.answers[i]?.trim());}
export const skillFor=(category:Category)=>({grammatica:'Taalvormen',spelling:'Spelling',lezen:'Lezen',luisteren:'Luisteren',schrijven:'Schrijven',formuleren:'Formuleren'}[category]);
