import type {Exercise,Question} from './exercises';
const q=(prompt:string,accepted:string[],explanation:string):Question=>({prompt,accepted,explanation});
export const grammarExercises:Exercise[]=[
 {id:'gram-lidwoorden',category:'grammatica',focus:'Lidwoorden',level:'A1',title:'De, het en een',description:'Leer een zelfstandig naamwoord samen met zijn lidwoord.',minutes:6,passage:'Een lidwoord staat voor een zelfstandig naamwoord: de tafel, het boek, een pen. In het meervoud gebruiken we de: de boeken. Verkleinwoorden in het enkelvoud krijgen het: het tafeltje. Leer bij nieuwe woorden steeds het lidwoord mee.',questions:[
 q('Vul de of het in: … boek',['het'],'Je leert de combinatie: het boek.'),q('Vul de of het in: … tafeltje',['het'],'Een verkleinwoord in het enkelvoud krijgt het.'),q('Vul de of het in: … boeken',['de'],'Bij een meervoud gebruiken we de.'),q('Vul de of het in: … tafel',['de'],'Je leert de combinatie: de tafel.')
 ]},
 {id:'gram-meervoud',category:'grammatica',focus:'Enkelvoud & meervoud',level:'A1',title:'Van één naar meer',description:'Maak meervouden en let op de klank van het woord.',minutes:7,passage:'Veel meervouden krijgen -en of -s. Boek wordt boeken, tafel wordt tafels. Soms verandert de spelling om de klank te bewaren: raam → ramen, pen → pennen. Niet alle woorden volgen één regel; leer nieuwe meervouden ook als woordpaar.',questions:[
 q('Eén boek, twee …',['boeken'],'Boek krijgt -en: boeken.'),q('Eén tafel, drie …',['tafels'],'Tafel krijgt -s: tafels.'),q('Eén raam, vier …',['ramen'],'De lange a-klank schrijf je in de open lettergreep ra- met één a.'),q('Eén pen, vijf …',['pennen'],'Door de dubbele n blijft de e kort: pen-nen.')
 ]},
 {id:'gram-nu',category:'grammatica',focus:'Tegenwoordige tijd',level:'A1',title:'Wat doe je vandaag?',description:'Kijk wie iets doet en kies de werkwoordsvorm.',minutes:7,passage:'In de tegenwoordige tijd gebruik je bij ik meestal de stam: ik werk. Bij jij en hij komt daar meestal een t bij: jij werkt. Staat jij achter de persoonsvorm, dan vervalt die t: werk jij? Bij wij gebruik je de vorm van het hele werkwoord: wij werken.',questions:[
 q('Ik … Nederlands. (leren)',['leer'],'Ik krijgt de stam: leer.'),q('Zij … vandaag. (werken, één persoon)',['werkt'],'Bij zij in het enkelvoud: stam + t.'),q('… jij morgen ook? (werken)',['werk'],'Jij staat achter de persoonsvorm; de t vervalt.'),q('Wij … in de klas. (oefenen)',['oefenen'],'Bij wij gebruik je de meervoudsvorm: oefenen.')
 ]},
 {id:'gram-verleden',category:'grammatica',focus:'Verleden tijd',level:'A2',title:'Vertel over gisteren',description:'Oefen de verleden tijd en herken onregelmatige vormen.',minutes:8,passage:'De verleden tijd vertelt wat vroeger gebeurde. Regelmatige werkwoorden krijgen -te(n) of -de(n): ik werkte, wij leerden. Andere werkwoorden veranderen van klank: lopen → liep, gaan → ging. Leer deze vormen mee bij het werkwoord.',questions:[
 q('Gisteren … ik tot vijf uur. (werken)',['werkte'],'Werken heeft de verleden tijd werkte.'),q('Vorige week … wij nieuwe woorden. (leren)',['leerden'],'Het onderwerp wij is meervoud: leerden.'),q('Gisteren … ik naar school. (gaan)',['ging'],'Gaan is onregelmatig: ik ging.'),q('Vroeger … zij elke dag naar haar werk. (lopen, één persoon)',['liep'],'Lopen is onregelmatig: zij liep.')
 ]},
 {id:'gram-toekomst',category:'grammatica',focus:'Toekomstige tijd',level:'A2',title:'Maak een plan voor morgen',description:'Gebruik gaan of zullen met een heel werkwoord.',minutes:7,passage:'Je kunt een plan maken met gaan + infinitief: morgen ga ik koken. Zullen kan onder andere een verwachting of toezegging uitdrukken: ik zal je bellen. Ook de tegenwoordige tijd kan naar later verwijzen: morgen werk ik. Het tijdwoord helpt de lezer.',questions:[
 q('Morgen … ik koken. (gaan)',['ga'],'Bij ik hoort ga; koken blijft de infinitief.'),q('Volgende week gaan wij … (verhuizen)',['verhuizen'],'Na gaan blijft het tweede werkwoord heel: verhuizen.'),q('Ik … je morgen bellen. (zullen)',['zal'],'Bij ik hoort zal.'),q('Morgen … hij thuis. (werken)',['werkt'],'De tegenwoordige tijd met morgen kan ook de toekomst uitdrukken.')
 ]},
 {id:'gram-tijden',category:'grammatica',focus:'Verleden tijd',level:'B1',title:'Toen, nu en straks',description:'Vertel een samenhangend verhaal met verschillende tijden.',minutes:8,passage:'Een tijdlijn helpt om je verhaal te ordenen. De voltooid verleden tijd beschrijft iets vóór een ander moment in het verleden: toen ik kwam, was zij al vertrokken. Bij een plan kun je gaan + infinitief gebruiken. Kijk steeds naar onderwerp, tijdwoord en volgorde.',questions:[
 q('Toen ik aankwam, … de les al begonnen. (zijn)',['was'],'Was begonnen ligt vóór aankwam.'),q('Gisteren … wij onze plannen. (bespreken)',['bespraken'],'Bespreken heeft de onregelmatige verleden tijd bespraken.'),q('Nu … ik beter wat de opdracht is. (begrijpen)',['begrijp'],'Bij ik hoort de stam begrijp.'),q('Morgen gaan wij de tekst … (herschrijven)',['herschrijven'],'Na gaan gebruik je de infinitief herschrijven.')
 ]}
];
