export const missions = [
 {id:'personal',title:'Jouw persoonlijke coach',category:'School & studie',level:'A1 – C2',time:10,role:'persoonlijke taalcoach',skill:'Zinsbouw',icon:'school',color:'orange',description:'Bespreek wat je vandaag wilt oefenen en werk aan een situatie uit jouw eigen leven.',goals:['Kies samen een concrete situatie','Oefen met je eigen woorden','Neem een bruikbare tip mee'],opening:'Hoi, ik ben Pip! We maken het Nederlands samen een beetje makkelijker. Wat wil je vandaag oefenen: iets op school, op je werk of in het dagelijks leven?'},
 {id:'mentor',title:'Een gesprek met je mentor',category:'School & studie',level:'A2 – B1',time:8,role:'mentor',skill:'Zinsbouw',icon:'school',color:'green',description:'Vertel hoe het met je studie gaat en vraag om hulp bij je planning.',goals:['Vertel hoe je studie gaat','Leg uit wat je lastig vindt','Maak samen een afspraak'],opening:'Hoi! Fijn dat je er bent. Neem rustig plaats. Hoe gaat het met je studie deze week?'},
 {id:'stage',title:'Je eerste dag op stage',category:'Stage & werk',level:'A2 – B1',time:6,role:'collega',skill:'Schooltaal',icon:'work',color:'orange',description:'Stel jezelf voor aan je collega en ontdek wat je vandaag gaat doen.',goals:['Stel jezelf voor','Vraag naar je werkzaamheden','Herhaal een instructie'],opening:'Welkom! Ik ben Sam, je collega. Leuk dat je bij ons begint. Kun je iets over jezelf vertellen?'},
 {id:'balie',title:'Een afspraak bij de gemeente',category:'Dagelijks leven',level:'A1 – A2',time:5,role:'baliemedewerker',skill:'Lidwoorden',icon:'home',color:'purple',description:'Leg uit waarvoor je komt en stel je vragen aan de balie.',goals:['Vertel waarvoor je komt','Vraag welke documenten nodig zijn','Maak een afspraak'],opening:'Goedemorgen, welkom bij de gemeente. Waarmee kan ik je helpen?'},
 {id:'presentatie',title:'Vertel over jouw idee',category:'School & studie',level:'B1 – B2',time:10,role:'docent',skill:'Schooltaal',icon:'school',color:'yellow',description:'Presenteer een idee en onderbouw je mening met voorbeelden.',goals:['Introduceer je idee','Geef twee argumenten','Beantwoord een kritische vraag'],opening:'Vandaag bespreken we jouw voorstel. Welk idee wil je aan de klas presenteren?'},
 {id:'winkel',title:'Iets ruilen in de winkel',category:'Dagelijks leven',level:'A2 – B1',time:5,role:'winkelmedewerker',skill:'Enkelvoud & meervoud',icon:'home',color:'pink',description:'Leg vriendelijk uit wat er mis is en zoek samen een oplossing.',goals:['Beschrijf je aankoop','Leg het probleem uit','Vraag om een oplossing'],opening:'Hallo! Kan ik je ergens mee helpen?'},
 {id:'overleg',title:'Meedenken in een overleg',category:'Stage & werk',level:'B2 – C1',time:10,role:'projectleider',skill:'Zinsbouw',icon:'work',color:'green',description:'Reageer op een voorstel en formuleer een onderbouwd alternatief.',goals:['Vat het voorstel samen','Noem een voor- en nadeel','Formuleer een alternatief'],opening:'Welkom bij het overleg. We willen de deadline een week vervroegen. Hoe kijk jij daartegenaan?'}
];
export const promptFor=(id:string,level:string)=>{const m=missions.find(m=>m.id===id)||missions[0];return `Je bent een warme, geduldige Nederlandse NT2-taalcoach. Je speelt de rol van ${m.role} in de situatie: ${m.description}. De leerling oefent op niveau ${level}. Spreek natuurlijk Nederlands met korte zinnen op dit niveau. Stel één vraag per beurt. Reageer op wat de leerling echt zegt, blijf in de situatie, verzin geen antwoorden van de leerling. Laat de leerling zelf praten. Geef af en toe één kleine behulpzame herformulering zonder het gesprek te onderbreken. Doelen: ${m.goals.join('; ')}. Geen opsommingen tijdens het roleplay, geen emoji. Je bent een AI, doe niet alsof je een echt mens bent. Geef geen echte medische of juridische adviezen.`;};
