import { sqliteTable, text, integer, index, uniqueIndex } from 'drizzle-orm/sqlite-core';
export const activities = sqliteTable('activities', {id:text('id').primaryKey(),userId:text('user_id').notNull(),kind:text('kind').notNull(),skill:text('skill').notNull(),xp:integer('xp').notNull(),date:text('date').notNull(),detail:text('detail').notNull()},table=>[index('idx_activities_user_date').on(table.userId,table.date)]);
export const lessons = sqliteTable('lessons',{id:text('id').primaryKey(),userId:text('user_id').notNull(),title:text('title').notNull(),module:text('module').notNull(),body:text('body').notNull(),status:text('status').notNull()},table=>[index('idx_lessons_user').on(table.userId)]);
export const profiles=sqliteTable('profiles',{userId:text('user_id').primaryKey(),data:text('data').notNull(),updatedAt:text('updated_at').notNull()});
export const news=sqliteTable('news',{id:text('id').primaryKey(),field:text('field').notNull(),title:text('title').notNull(),url:text('url').notNull(),source:text('source').notNull(),publishedAt:text('published_at').notNull(),selectedAt:text('selected_at').notNull(),week:text('week').notNull()},t=>[uniqueIndex('idx_news_field_week').on(t.field,t.week)]);

export const exerciseWork=sqliteTable('exercise_work',{id:text('id').primaryKey(),userId:text('user_id').notNull(),exerciseId:text('exercise_id').notNull(),data:text('data').notNull(),completed:integer('completed').notNull().default(0),updatedAt:text('updated_at').notNull()},t=>[index('idx_exercise_work_user').on(t.userId)]);
export const learningState=sqliteTable('learning_state',{userId:text('user_id').primaryKey(),plan:text('plan'),draft:text('draft'),updatedAt:text('updated_at').notNull()});
export const learningEntries=sqliteTable('learning_entries',{id:text('id').primaryKey(),userId:text('user_id').notNull(),data:text('data').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('idx_learning_entries_user_date').on(t.userId,t.updatedAt)]);
export const learningAssessments=sqliteTable('learning_assessments',{id:text('id').primaryKey(),userId:text('user_id').notNull(),data:text('data').notNull(),createdAt:text('created_at').notNull()},t=>[index('idx_learning_assessments_user_date').on(t.userId,t.createdAt)]);
export const learningEvidence=sqliteTable('learning_evidence',{id:text('id').primaryKey(),userId:text('user_id').notNull(),data:text('data').notNull(),createdAt:text('created_at').notNull()},t=>[index('idx_learning_evidence_user_date').on(t.userId,t.createdAt)]);
export const users=sqliteTable('users',{id:text('id').primaryKey(),email:text('email').notNull(),displayName:text('display_name').notNull(),role:text('role').notNull().default('student'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[uniqueIndex('idx_users_email').on(t.email)]);
export const classrooms=sqliteTable('classrooms',{id:text('id').primaryKey(),teacherId:text('teacher_id').notNull(),name:text('name').notNull(),description:text('description').notNull().default(''),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('idx_classrooms_teacher').on(t.teacherId)]);
export const classroomMembers=sqliteTable('classroom_members',{classroomId:text('classroom_id').notNull(),studentId:text('student_id').notNull(),joinedAt:text('joined_at').notNull()},t=>[uniqueIndex('idx_classroom_member').on(t.classroomId,t.studentId),index('idx_members_student').on(t.studentId)]);
