'use client';
import {useState,type FormEvent} from 'react';
import {supabaseBrowser} from '@/lib/supabase/browser';
export function LoginForm({next,confirmationError,configured,demo}:{next:string;confirmationError:boolean;configured:boolean;demo:boolean}){
 const [signup,setSignup]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(confirmationError?'De bevestigingslink is verlopen of al gebruikt. Probeer in te loggen.':''),[email,setEmail]=useState(''),[password,setPassword]=useState('');
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');try{const auth=supabaseBrowser().auth;const result=signup?await auth.signUp({email,password,options:{emailRedirectTo:location.origin+'/auth/callback?next='+encodeURIComponent(next)}}):await auth.signInWithPassword({email,password});if(result.error){setMessage(result.error.code==='invalid_credentials'?'Je e-mailadres of wachtwoord klopt niet.':result.error.code==='email_not_confirmed'?'Bevestig eerst je e-mailadres via de ontvangen link.':result.error.status===429?'Te veel pogingen. Wacht even en probeer opnieuw.':'Aanmelden lukte niet. Controleer je gegevens en probeer opnieuw.');return;}if(result.data.session){location.assign(next)}else setMessage('Controleer je e-mail en bevestig je account. Kom daarna hier terug om in te loggen.');}catch{setMessage('Verbinding maken lukte niet. Probeer het opnieuw.')}finally{setBusy(false)}}
 async function guest(){setBusy(true);setMessage('');try{const {error}=await supabaseBrowser().auth.signInAnonymously();if(error)setMessage('De gastdemo is tijdelijk niet beschikbaar. Maak een account aan of probeer later opnieuw.');else location.assign(next)}catch{setMessage('Verbinding maken lukte niet.')}finally{setBusy(false)}}
 return <main style={{minHeight:'100svh',display:'grid',placeItems:'center',padding:24,background:'#faf8f3',color:'#292d28',fontFamily:'Arial,sans-serif'}}><section style={{width:'100%',maxWidth:440,padding:32,background:'white',borderRadius:24,boxShadow:'0 16px 60px #34382f0d'}}><a href="/welkom" style={{color:'#98492f'}}>← AI Taalcoach</a><h1 style={{fontSize:32,margin:'28px 0 12px'}}>{signup?'Jouw eerste stap.':'Fijn dat je terug bent.'}</h1><p style={{lineHeight:1.7,marginBottom:24}}>Je eigen leerplek, op jouw tempo.</p>{!configured?<p role="status">De online leeromgeving wordt nog ingericht. Kom binnenkort terug.</p>:<><form onSubmit={submit}><label style={{display:'block',marginBottom:16}}>E-mailadres<input autoComplete="email" type="email" required value={email} onChange={e=>setEmail(e.target.value)} style={inputStyle}/></label><label style={{display:'block',marginBottom:16}}>Wachtwoord<input autoComplete={signup?'new-password':'current-password'} type="password" minLength={8} required value={password} onChange={e=>setPassword(e.target.value)} style={inputStyle}/></label>{signup&&<p style={{fontSize:13,marginBottom:16}}>Gebruik minstens 8 tekens. Je ontvangt een bevestiging per e-mail.</p>}<button disabled={busy} style={buttonStyle}>{busy?'Even geduld…':signup?'Account aanmaken':'Inloggen'}</button></form><p role="status" style={{lineHeight:1.6,marginTop:16}}>{message}</p><button disabled={busy} onClick={()=>{setSignup(!signup);setMessage('')}} style={{marginTop:16,color:'#98492f',textDecoration:'underline'}}>{signup?'Ik heb al een account':'Nog geen account? Maak er een aan'}</button>{demo&&<div style={{borderTop:'1px solid #e8e5df',marginTop:24,paddingTop:24}}><button disabled={busy} onClick={guest} style={{...buttonStyle,background:'#eef1e9',color:'#34382f'}}>Probeer als gast</button><p style={{fontSize:13,lineHeight:1.6,marginTop:12}}>Een eigen demosessie zonder e-mailadres. Na uitloggen kun je deze voortgang niet terughalen. Gebruik alleen fictieve gegevens.</p></div>}</>}</section></main>
}
const inputStyle={display:'block',width:'100%',marginTop:8,padding:12,border:'1px solid #d6d8d1',borderRadius:10,fontSize:16};
const buttonStyle={width:'100%',padding:14,borderRadius:12,background:'#98492f',color:'white',fontWeight:600,cursor:'pointer'};
