'use client';
import {useEffect,useRef,useState} from 'react';
import {MessageCircle,BookOpen,Mic,Check,Sparkles,Play,Pause,Plus,Minus,Menu,X,PenLine,Headphones,Gamepad2,CalendarDays} from 'lucide-react';
import {coachCharacters} from '@/lib/coach-preferences';
import './landing.css';
export function LandingPage({signInUrl,signedIn=false}:{signInUrl:string;signedIn?:boolean}){
 const root=useRef<HTMLDivElement>(null),[menu,setMenu]=useState(false),[motion,setMotion]=useState(true),[character,setCharacter]=useState(0),[answer,setAnswer]=useState<string|null>(null),[faq,setFaq]=useState<number|null>(null);
 const start=signedIn?'/app':signInUrl;
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');setMotion(!media.matches);const update=()=>setMotion(!media.matches);media.addEventListener('change',update);return()=>media.removeEventListener('change',update)},[]);
 useEffect(()=>{const el=root.current;if(!el)return;let frame=0;const update=()=>{frame=0;const scroll=window.scrollY;el.style.setProperty('--landing-scroll',String(Math.min(1,scroll/650)));};const onScroll=()=>{if(!frame)frame=requestAnimationFrame(update)};update();if(motion)window.addEventListener('scroll',onScroll,{passive:true});else el.style.setProperty('--landing-scroll','0');return()=>{window.removeEventListener('scroll',onScroll);cancelAnimationFrame(frame)}},[motion]);
 useEffect(()=>{const items=root.current?.querySelectorAll('[data-reveal]');if(!items)return;const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');observer.unobserve(e.target)}}),{threshold:.12});items.forEach(e=>observer.observe(e));return()=>observer.disconnect()},[]);
 const faqs=[['Voor wie is AI Taalcoach?','Voor volwassenen die Nederlands als tweede taal leren. Bijvoorbeeld voor inburgering, een opleiding of situaties op je werk en in het dagelijks leven. Je kiest zelf je leerdoel.'],['Moet ik iets installeren?','Je gebruikt het platform in je browser. Veel oefeningen werken direct. Voor de AI-coach laad je eenmalig een taalmodel op je apparaat (ongeveer 2,5 GB). Gebruik daarvoor een browser met WebGPU, zoals een recente Chrome of Edge.'],['Heb ik al goed Nederlands nodig?','Nee. Je vindt oefeningen vanaf A1. Met een korte taalcheck en je oefenresultaten krijg je een voorlopig niveauadvies. Dat helpt je kiezen; het is geen officieel examen.'],['Hoe maak ik een account aan?','Je gaat verder met je ChatGPT-account. Bij je eerste aanmelding ontstaat je persoonlijke leerprofiel. Heb je nog geen ChatGPT-account, dan kun je dat via de aanmeldpagina aanmaken.'],['Geeft de AI mij gewoon het antwoord?','Je coach stelt vragen en geeft aanwijzingen, zodat jij zelf verder kunt. Er zijn ook vaste oefeningen met uitleg en feedback. AI kan fouten maken; bespreek twijfels met je docent.']];
 return <div className="tc-landing" ref={root} data-animate={motion}>
 <a href="#landing-main" className="landing-skip">Naar de inhoud</a>
 <header className="landing-nav"><a className="landing-brand" href="/welkom" aria-label="AI Taalcoach startpagina"><span><MessageCircle size={23}/></span>taalcoach<sup>AI</sup></a><nav aria-label="Hoofdnavigatie" className={menu?'landing-links open':'landing-links'}><a href="#ontdek" onClick={()=>setMenu(false)}>Ontdek</a><a href="#zo-werkt-het" onClick={()=>setMenu(false)}>Zo werkt het</a><a href="#vragen" onClick={()=>setMenu(false)}>Veelgestelde vragen</a></nav><div className="landing-nav-actions"><a className="landing-login" href={start} target="_top">{signedIn?'Mijn leerplek':'Inloggen'}</a><a className="landing-button landing-button-small" href={start} target="_top">{signedIn?'Verder oefenen':'Begin met leren'}</a><button className="landing-menu" onClick={()=>setMenu(!menu)} aria-label={menu?'Menu sluiten':'Menu openen'} aria-expanded={menu}>{menu?<X/>:<Menu/>}</button></div></header>
 <main id="landing-main">
 <section className="landing-hero"><div className="landing-hero-copy"><span className="landing-kicker"><span/>NEDERLANDS VOOR JOUW VOLGENDE STAP</span><h1>Meer woorden.<br/><span>Meer wereld.</span></h1><p>Voor dat gesprek. Die opleiding. Jouw toekomst.<br className="landing-desktop-break"/> Oefen Nederlands op jouw tempo, met een taalmaatje naast je.</p><div className="landing-hero-actions"><a className="landing-button" href={start} target="_top">{signedIn?'Naar mijn leerplek':'Maak je leerprofiel'}</a><a href="#ontdek" className="landing-secondary"><Play size={15} fill="currentColor"/> Ontdek de taalcoach</a></div><span className="landing-caption">Gewoon in je browser. Helemaal op jouw tempo.</span></div>
 <div className="landing-preview-stage"><div className="landing-preview-glow"/><div className="landing-preview"><div className="landing-preview-bar"><span/><span/><span/><small>Jouw persoonlijke leeromgeving</small></div><img src="/landing/platform-preview.png" width={1360} height={960} fetchPriority="high" alt="Voorbeeld van AI Taalcoach met een persoonlijke leerroute, oefeningen en een taalmaatje"/></div><div className="landing-float landing-float-coach"><img src="/mascot/pip-vos.png" width={72} height={72} alt="Pip de vos"/><span><b>Een klein zetje.</b><small>Jij doet het denkwerk.</small></span></div><div className="landing-float landing-float-progress"><Check size={18}/><span>Elke kleine stap telt.</span></div></div>
 <div className="landing-audiences"><span>JOUW NEDERLANDS. JOUW DOEL.</span><p>Inburgering <i/> Studie <i/> Werk <i/> Elke dag</p></div></section>
 <section id="ontdek" className="landing-discover landing-section"><div className="landing-section-heading" data-reveal><span className="landing-kicker">LEREN DAT BIJ JE LEVEN PAST</span><h2>Niet alleen weten.<br/><span>Ook durven doen.</span></h2><p>Een bericht schrijven. Je mening uitleggen. Begrijpen wat iemand zegt. Je oefent de taal die je echt gebruikt.</p></div><div className="landing-feature-grid"><article className="landing-practice-card" data-reveal><div className="landing-card-heading"><BookOpen size={22}/><span>WOORDEN WORDEN VAARDIGHEDEN</span></div><h3>Probeer het maar.</h3><p>Eén zin. Een kleine stap vooruit.</p><div className="landing-demo"><span>VUL HET JUISTE WOORD IN</span><p>Gisteren <em>{answer==='ging'?'ging':'…'}</em> ik naar school.</p><div role="group" aria-label="Kies het juiste werkwoord">{['ga','ging','gaan'].map(a=><button key={a} onClick={()=>setAnswer(a)} aria-pressed={answer===a} className={answer===a?(a==='ging'?'correct':'retry'):''}>{a}{answer===a&&a==='ging'&&<Check size={16}/>}</button>)}</div><div className="landing-demo-feedback" aria-live="polite">{answer?answer==='ging'?'Precies! ‘Gisteren’ vertelt dat het al gebeurd is.':'Kijk naar ‘gisteren’. Welke vorm hoort bij iets dat al gebeurd is?':'Kies een woord. Fouten maken mag.'}</div>{answer&&<button className="landing-reset" onClick={()=>setAnswer(null)}>Nog een keer</button>}</div><div className="landing-skill-tags"><span>Spelling</span><span>Lezen</span><span>Luisteren</span><span>Schrijven</span><span>Formuleren</span><span>Grammatica</span></div></article>
 <article className="landing-character-card" data-reveal><div className="landing-card-heading"><Sparkles size={22}/><span>EEN COACH DIE BIJ JE PAST</span></div><h3>Jouw taalmaatje.<br/>Jouw eigen stijl.</h3><div className="landing-character"><img key={character} src={coachCharacters[character].image} width={230} height={230} alt={coachCharacters[character].description}/><div className="landing-speech">“{coachCharacters[character].greeting}”</div></div><div className="landing-character-options" role="group" aria-label="Bekijk de coachpersonages">{coachCharacters.map((c,i)=><button key={c.id} aria-pressed={character===i} onClick={()=>setCharacter(i)}><img src={c.image} alt="" width={42} height={42}/>{c.label}</button>)}</div><p>Kies een personage, geef het een naam en praat of typ. Je coach geeft hints, zodat jij zelf verder komt.</p></article></div></section>
 <section id="zo-werkt-het" className="landing-journey landing-section"><div className="landing-section-heading" data-reveal><span className="landing-kicker">VAN EERSTE STAP TOT VOLGENDE STAP</span><h2>Een leerplek.<br/><span>Heel veel mogelijkheden.</span></h2></div><div className="landing-journey-layout"><div className="landing-sticky" data-reveal><div className="landing-mini-plan"><span className="landing-kicker">MIJN LEERROUTE</span><h3>Ruimte voor<br/>jouw groei.</h3><div><Check/><span><b>Ontdek je startpunt</b><small>Jouw taalprofiel</small></span></div><div><PenLine/><span><b>Schrijf een kort verhaal</b><small>Creatief oefenen · 10 min</small></span></div><div><Mic/><span><b>Oefen een gesprek</b><small>In je eigen woorden</small></span></div><span className="landing-plan-note">Voorbeeld van een persoonlijke leerroute</span></div></div><div className="landing-steps"><article data-reveal><span>01</span><div><h3>Begin waar jij bent.</h3><p>Vertel wat je wilt bereiken. Een korte taalcheck geeft een eerste richting, en je leeradvies beweegt mee met je oefeningen.</p></div></article><article data-reveal><span>02</span><div><h3>Maak het van jou.</h3><p>Kies je interesses, je coach en je kleuren. Lees een verhaal, schrijf bij een tekening of oefen met nieuws uit jouw vakgebied.</p></div></article><article data-reveal><span>03</span><div><h3>Blijf in beweging.</h3><p>Plan kleine oefenmomenten, speel een taalspel en kijk terug op wat je al kunt. Je hoeft het niet in één keer goed te doen.</p></div></article></div></div></section>
 <section className="landing-everyday" data-reveal><span className="landing-kicker">KLEINE STAPPEN. GROOT VERSCHIL.</span><h2>Vandaag een zin.<br/>Morgen een gesprek.</h2><div><span><Headphones/> Luister</span><span><PenLine/> Schrijf</span><span><MessageCircle/> Praat</span><span><Gamepad2/> Speel</span><span><CalendarDays/> Groei</span></div></section>
 <section id="vragen" className="landing-faq landing-section"><div data-reveal><span className="landing-kicker">NOG EVEN DIT</span><h2>Een goed begin<br/>begint met een vraag.</h2></div><div className="landing-faq-list">{faqs.map(([q,a],i)=><article key={q}><h3><button aria-expanded={faq===i} aria-controls={`landing-faq-${i}`} onClick={()=>setFaq(faq===i?null:i)}>{q}{faq===i?<Minus size={20}/>:<Plus size={20}/>}</button></h3><div id={`landing-faq-${i}`} hidden={faq!==i}><p>{a}</p></div></article>)}</div></section>
 <section className="landing-final" data-reveal><img src="/mascot/pip-vos.png" width={100} height={100} alt=""/><span className="landing-kicker">JE HOEFT HET NIET ALLEEN TE DOEN</span><h2>Jouw volgende<br/>stap begint hier.</h2><a className="landing-button" href={start} target="_top">{signedIn?'Verder met leren':'Account aanmaken'}</a><p>{signedIn?'Je leerplek staat voor je klaar.':<>Heb je al een account? <a href={signInUrl} target="_top">Log in</a></>}</p>{!signedIn&&<small>Je gaat veilig verder met je ChatGPT-account.</small>}</section>
 </main><footer className="landing-footer"><a className="landing-brand" href="/welkom"><span><MessageCircle size={20}/></span>taalcoach<sup>AI</sup></a><p>Op jouw tempo. In jouw woorden.</p><button onClick={()=>setMotion(!motion)} aria-pressed={!motion}>{motion?<Pause size={15}/>:<Play size={15}/>} {motion?'Minder beweging':'Animaties aan'}</button></footer>
 </div>
}
